### PR TITLE
When collecting measures, do not emit "empty" metrics (i.e. Int64SummaryData where count=0).

### LINKED ISSUE #1666: Incorrect min/max for Int64SummaryData
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
OpenTelemetry.Exporter.Prometheus Version="1.0.0-rc1.1"

Runtime version (e.g. `net461`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

*

## Symptom

It appears that when the metric value is 0 for a MeasureMetric<long> the Min and Max get something that looks like an overflow. This is intermittent or at least when the measure is zero.

**What is the expected behavior?**

Sum, Min and Max should be correct.

**What is the actual behavior?**

Sum = 0
Max = -9223372036854775808
Min = 9223372036854775807

(the min and max aren't reversed)

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

### Create new class

```
 private class UngroupedBatcherWithSumFix: UngroupedBatcher
        {
            private readonly ILogger _logger;

            /// <summary>
            /// Initializes a new instance of the <see cref="UngroupedBatcher"/> class.
            /// </summary>
            public UngroupedBatcherWithSumFix(ILogger logger)
            {
                _logger = logger;
            }

            /// <inheritdoc/>
            public override void Process(Metric metric)
            {
                //HACK: Why is this happening?
                #region Hack for min/max

                if (metric.Data
                    .Where(d => d is Int64SummaryData)
                    .Cast<Int64SummaryData>()
                    .Any(d => d.Max == Int64.MinValue && d.Min == Int64.MaxValue))
                {
                    //throw away useless metric
                    _logger.LogWarning($"Tossing bad metric for {metric.MetricName}");
                    return;
                }

                if (metric.Data
                    .Where(d => d is DoubleSummaryData)
                    .Cast<DoubleSummaryData>()
                    .Any(d => d.Max == double.MinValue && d.Min == double.MaxValue))
                {
                    //throw away useless metric
                    _logger.LogWarning($"Tossing bad metric for {metric.MetricName}");
                    return;
                }
                #endregion

                base.Process(metric);
            }
        }
```

### Stand up the exporter
```
            var portString = _configuration[ConfigurationKeys.MetricEndpoint.Port];

            var port = !string.IsNullOrWhiteSpace(portString) ? Convert.ToInt32(portString) : 9091;

            // Create and Setup Prometheus Exporter
            var promOptions = new PrometheusExporterOptions
            {
                Url = $"http://localhost:{port}/metrics/"
            };
            var promExporter = new PrometheusExporter(promOptions);
            //TODO: Create Processor (called Batcher in Metric spec, this is still not decided)
            var processor = new UngroupedBatcherWithSumFix();

            // Application which decides to enable OpenTelemetry metrics
            // would setup a MeterProvider and make it default.
            // All meters from this factory will be configured with the common processing pipeline.
            int pushIntervalInSecs = 15;
            MeterProvider.SetDefault(Sdk.CreateMeterProviderBuilder()
                .SetProcessor(processor)
                .SetExporter(promExporter)
                .SetPushInterval(TimeSpan.FromSeconds(pushIntervalInSecs))
                .Build());
```
We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

### PR DESCRIPTION
**Pull request by victlu**
Fixes #1666 

## Changes

When collecting measures, do not emit "empty" metrics (i.e. Int64SummaryData where count=0).

For an "empty" Int64SummaryData, the min/max fields are initialized to values that causes confusion for users.

### CODE REVIEW

File: src/OpenTelemetry/Metrics/MeterSdk.cs [hunk 1]
```diff
@@ -159,8 +159,18 @@ public virtual void Collect()
...
+                        if (metricData is Int64SummaryData summary)
+                        {
+                            haveData = summary.Count > 0;
+                        }
+
+                        if (haveData)
+                        {
+                            metricData.Labels = labelSet.Labels;
+                            metric.Data.Add(metricData);
+                        }
```
Comment (bruno-garcia) [inline src/OpenTelemetry/Metrics/MeterSdk.cs:173]: Do we have C# 9 already in?

```suggestion
                        if (metricData is Int64SummaryData {Count>0} summary)
                        {
                            metricData.Labels = labelSet.Labels;
                            metric.Data.Add(metricData);
                        }
```

Comment (victlu) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: I assume we can use C# 9 syntax.  And if not, our CI should fail.

In this case, I was being extra careful in the case that metricData is NOT an Int64SummaryData.  Thus, I am "filtering" only if I am positively assured it's a SummaryData with count=0.  Otherwise, I don't want to alter behavior.

I think we are generally not handling "empty" collect/export cycles correctly.  We still emit "empty" records (for both Measures and Sum).  Ideally, I think we would not even create a new Metric (with Data.Count = 0) to pass to Processors.  In the SumData case, I think we need to include a Count field, so we can distinguish between having/not-having reported data.  (i.e. Empty case (sum=0, 0 data point) vs multiple data points where sum=0)

However, I am new to this code base, so please provide feedback for such.

Comment (bruno-garcia) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: oh I see what you did (and I broke) now. I haven't been reviewing code here (or writing) in months so, better wait for someone else to give proper feedback here.

Comment (eddynaka) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: another option:
```csharp
 if (metricData is Int64SummaryData summary && summary.Count > 0)
                        {
                            metricData.Labels = labelSet.Labels;
                            metric.Data.Add(metricData);
                        }
```

Comment (bruno-garcia) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: The catch here is that he started with `var haveData = true;`. So he wants to add the value by default, but in case it's `Int64SummaryData`, only if it's `Count>0`.

Comment (CodeBlanch) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: Would it be helpful to add `HasData` on the `MetricData` base class?
```csharp
public abstract class MetricData
{
   public virtual bool HasData => true;
}

public class Int64SummaryData
{
   public override bool HasData => Count > 0;
}
```

Allowing for this code here to just be:
```csharp
                        if (metricData.HasData)
                        {
                            metricData.Labels = labelSet.Labels;
                            metric.Data.Add(metricData);
                        }
```

Comment (victlu) [reply src/OpenTelemetry/Metrics/MeterSdk.cs:173]: Yes, I would also agree.  We currently cannot distinguish an "empty" Int64SummaryData (and also Int64SumData).  If we added HasData, it will definitely be easier.  This will also help with us emitting unnecessary "empty" Int64SumData as well.  I will refactor accordingly.

**Comment by victlu** [comment]
Ping

File: src/OpenTelemetry/Metrics/Aggregators/Aggregator.cs [hunk 2]
```diff
@@ -28,31 +28,44 @@ namespace OpenTelemetry.Metrics.Aggregators
...
             // checkpoints the start time for the current aggregation, and sets the new start time.
-            this.checkpointStartTimeTicks = Interlocked.Exchange(ref this.startTimeTicks, DateTimeOffset.UtcNow.Ticks);
+            this.checkpoint = Interlocked.Exchange(ref this.active, new AggState());
+        }
+
+        /// <summary>
+        /// Check if checkpoint has any aggregated data.
+        /// </summary>
+        /// <returns>true if data was presented to aggregator.</returns>
+        public virtual bool HasData()
```
Comment (CodeBlanch) [inline src/OpenTelemetry/Metrics/Aggregators/Aggregator.cs:62]: Couple of questions...
* Any reason you went with method over property (`public virtual bool HasData => this.checkpoint.Count > 0;`)?
* Should we call it `HasCheckpointData`? Just looking at the code it looks like there's actually 2 counts in play (`active` & `checkpoint`).

Comment (victlu) [reply src/OpenTelemetry/Metrics/Aggregators/Aggregator.cs]: I try to follow the style in existing code.  In this section of code, I do not see much use of Properties.  I am not that opinionated on this topic, so if you prefer, I can change to property.

**Comment by victlu** [comment]
# On a separate note:

We split CheckPoint() call from getting info about the checkpoints.  (i.e. CheckPoint(), then, HasCheckPointData(), GetLast*Timestamp(), ToMetricData())  This potentially introduce a race-condition when Checkpoint() is called frequently.

I think this area of code should be refactor such that Checkpoint() is atomic, and will return the FULL state of this checkpoint.

**Review by CodeBlanch — APPROVED** [review]
LGTM

File: src/OpenTelemetry/Metrics/Aggregators/Aggregator.cs (hunk 2 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Metrics/Aggregators/Aggregator.cs]: I don't feel strongly about it either, was mostly just curious 😄
