### PR TITLE
Batching Activity Processor fixes by Eddy & Mike

### LINKED ISSUE #769: Revise dispose pattern in SpanProcessor/ActivityProcessor
`Dispose` pattern in `SimpleSpanProcessor`, `SimpleActivityProcessor`, `BatchingSpanProcessor` and `BatchingActivityProcessor` needs to be revised. As @reyang mentioned `ShutdownAsync` is not thread safe, race condition could happen for this.stopping, and it would re-enter to re-execute the same code. 

Raised as a part of PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/755#discussion_r448119691

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #769 

## Changes

* I was reviewing #842 and I noticed there were some bigger issues in the `BatchingActivityProcessor` class. Primarily `ForceFlush` and the background thread can both try to export at the same time which will cause a race on the `this.batch` list. This PR is trying to fix the threading & disposal patterns in there to eliminate some of the underlying issues. Modeled after `JaegerUdpBatcher`.
* Updated `SimpleActivityProcessor` to call shutdown on dispose.

### CODE REVIEW

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs [hunk 1]
```diff
@@ -87,18 +89,30 @@ public BatchingActivityProcessor(ActivityExporter exporter, int maxQueueSize, Ti
...
 
-            this.cts = new CancellationTokenSource();
             this.exportQueue = new ConcurrentQueue<Activity>();
 
-            // worker task that will last for lifetime of processor.
-            // Threads are also useless as exporter tasks run in thread pool threads.
-            Task.Run(() => this.Worker(this.cts.Token), this.cts.Token);
+            this.flushTimer = new System.Timers.Timer
+            {
+                AutoReset = false,
```
Comment (cijothomas) [inline src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:107]: What does this mean? Timer.Elapsed is triggered only once? How does it keep getting trigger at every Interval?

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs [hunk 2]
```diff
@@ -188,21 +182,74 @@ protected virtual void Dispose(bool isDisposing)
...
+                this.flushTimer.Dispose();
+                this.flushLock.Dispose();
+                this.isDisposed = true;
             }
         }
 
-        private async Task ExportBatchAsync(CancellationToken cancellationToken)
+        private async Task FlushAsyncInternal(bool drain, CancellationToken cancellationToken)
         {
+            await this.flushLock.WaitAsync(cancellationToken).ConfigureAwait(false);
```
Comment (cijothomas) [inline src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: Is it possible to unit test the scenario where multiple Flush is called from the timer itself? i.e one Timer event is still not finished (slooowww export) and the next one is fired?

Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: Check out my comment about the timer. Given that behavior, you think it's still needed?

Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: which comment?

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs (hunk 1 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:107]: When the flush fires, the ~first thing it does is disable the timer:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/8ec6e7928d2a2034b663bea57ea8fbb042d844a6/src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs#L195-L201

When it completes its work, it turns it back on:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/8ec6e7928d2a2034b663bea57ea8fbb042d844a6/src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs#L241-L247

Let me know what you think about that as a mechanism.

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs (hunk 2 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: Hah forgot to send. Should be there now.

Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: makes sense.

Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: Does the timer mechanism now keeps firing at regular, fixed intervals? or the timer "stop counter" when Enabled = false;?

Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:197]: if interval is d, then do we always export at T, T+d, T+2d? or T, T+(flush duration1)+d, T + (flush duration2) + d and so on.

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs [hunk 3]
```diff
@@ -188,21 +219,80 @@ protected virtual void Dispose(bool isDisposing)
...
+                this.isDisposed = true;
             }
         }
 
-        private async Task ExportBatchAsync(CancellationToken cancellationToken)
+        private async Task FlushAsyncInternal(bool drain, bool lockAlreadyHeld, CancellationToken cancellationToken)
         {
+            if (!lockAlreadyHeld)
+            {
+                await this.flushLock.WaitAsync(cancellationToken).ConfigureAwait(false);
```
Comment (xiang17) [inline src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:236]: What's the expected behavior if `cancellationToken` is canceled for the token passed from `ForceFlushAsync` and `ShutdownAsync`?

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs (hunk 2 above)
Comment (eddynaka) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs]: @cijothomas , that would be true unless the flush takes more then d time. Because only after flushing it would enable again.

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs (hunk 3 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:236]: @xiang17 Good question!

## Short answer
Spans are dropped on cancellation.

## Long answer

I feel like if someone passes a `cancellationToken` to an async operation, in general, their expectation is the operation will be aborted if/when cancellation is triggered, as soon as it is possible to do so. So what I'm trying to do with this work is make sure we at least attempt to honor that. In our case what is being aborted is the export of spans. Currently, we do not re-try the transmission of spans. If an exporter throws an error, which could be timeout or cancellation, the spans are lost. I think that is probably the correct behavior. Otherwise, we would continue to hold them in memory likely starving the process at some point and preventing the user's real work from executing.

**BatchingSpanProcessor**

The BatchingSpanProcessor has a timeout for calling export (default 30 seconds). This concept comes from the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#batching-processor). When it asks an exporter to "Export" a batch, it creates a cancellation token for that time and passes it to the exporter. It is up to the exporter to decide what to do with that token (see below). One of the changes I'm making on this PR is, if the user passes a cancellationToken, I create a linked token from the export timeout & the user's token. So if the user cancels the operation, or the timeout is reached, we will signal a cancel to the exporter.

When OpenTelemetry is disposed we will call shutdown, without passing a cancellationToken. But there is still the export timeout. So on shutdown, we will attempt to flush any remaining spans up to the export timeout, at which point we will signal to the exporter to cancel.

**Zipkin & Jaeger Exporters**

Today Zipkin & Jaeger Exporters do not respect the cancellationToken passed on the export call. You will see a comment like this one:

   https://github.com/open-telemetry/opentelemetry-dotnet/blob/a3c0b80840ff780826c311bb5b25e1c24c278815/src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs#L58-L59

   I haven't pushed it yet, but I'm working on fixing Zipkin & Jaeger Exporters so they honor the cancellation. The current behavior seems contrary to the spec (see below).

**Other Exporters**

AFAIK, it's up to the implementation. The spec says:
```
Export() must not block indefinitely, there must be a reasonable upper limit
after which the call must time out with an error result (`Failure`).

Any retry logic that is required by the exporter is the responsibility
of the exporter. The default SDK SHOULD NOT implement retry logic, as
the required logic is likely to depend heavily on the specific protocol
and backend the spans are being sent to.
```

@cijothomas @reyang @pjanotti @SergeyKanzhelev @MikeGoldsmith Would love to hear your thoughts on this as well.

Comment (xiang17) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:236]: Thanks for the informative answer!

My concern is that client code might crash from an `OperationCanceledException`, which might be thrown by `ForceFlushAsync` or `ShutdownAsync` for calling [SemaphoreSlim.WaitAsync(CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync?view=netcore-3.1#System_Threading_SemaphoreSlim_WaitAsync_System_Threading_CancellationToken_)

Whose responsibility is it to handle the cancellation exception? The exporter or SDK?

Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:236]: I get what you are asking. No, the SDK should never throw! The cases where the SDK is calling `ForceFlushAsync` or `ShutdownAsync` it either has a try/catch or isn't passing a cancellationToken. Meaning, it won't throw.

If you are asking, why don't we have a try/catch in `ForceFlushAsync` or `ShutdownAsync`? That's a public API technically the user can call it. I don't take "the SDK should never throw" to mean we should have a try/catch over every line of code :smile: User calling the APIs isn't really the SDK throwing. If the user calls one of those methods and specifies a real cancellationToken, wouldn't the expectation be an `OperationCanceledException` is possible?

Anyway, you have me worried and I'm going to spend more time on the edge cases. Please bring up any code paths you see where it could throw! To be honest, I'm not really sure what should happen if the user did not specify a cancellationToken, but our internal export timeout cancellationToken is triggered. Probably should bubble up a TimeoutException for that?

Comment (reyang) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:236]: > No, the SDK should never throw!

I think the SDK should throw if the arguments passed in is invalid **during initialization** (e.g. null string passed in where it doesn't make sense at all, percentage sampler initialized using a negative number).
```csharp
        using var otel = OpenTelemetrySdk.EnableOpenTelemetry(b => b
            .AddActivitySource(null)
            .UseConsoleExporter(options => options.DisplayAsJson = true));
```

Once initialized, the SDK should never punish the user by throwing random exceptions, except for **real exceptions** such like OOM and stack overflow.

Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:244]: Update. I did some testing and polished this up. The current behavior is, if a cancellationToken is passed in, we'll allow the OperationCanceledException to bubble up. All other exceptions will be caught and logged. A special log event was added for exporter timeout.

File: src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs [hunk 4]
```diff
@@ -72,13 +70,23 @@ public JaegerUdpBatcher(JaegerExporterOptions options, TTransport clientTranspor
 
             this.maxFlushIntervalTimer.Elapsed += async (sender, args) =>
             {
+                bool lockTaken = this.flushLock.Wait(0);
```
Comment (CodeBlanch) [inline src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs:73]: This is an optimization I added in BatchingActivityProcessor & JaegerUdpBatcher. If the timer fires, and the flush lock is already held, it will just return, releasing the thread instead of blocking. The idea being, when the running flush finishes it will restart the timer anyway. This should eliminate a bunch of threads stacking up waiting on the lock.

File: src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs [hunk 5]
```diff
@@ -87,7 +95,50 @@ public JaegerUdpBatcher(JaegerExporterOptions options, TTransport clientTranspor
 
         internal Dictionary<string, Batch> CurrentBatches { get; } = new Dictionary<string, Batch>();
 
-        public async ValueTask<int> AppendAsync(JaegerSpan jaegerSpan, CancellationToken cancellationToken)
+        public async ValueTask<int> AppendBatchAsync(IEnumerable<Activity> activityBatch, CancellationToken cancellationToken)
```
Comment (CodeBlanch) [inline src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs:98]: This is an optimization in JaegerUdpBatcher. Before it would acquire the lock for each Span/Activity in the batch. I moved it up a level higher. Should improve perf.

File: src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs [hunk 6]
```diff
@@ -37,36 +36,23 @@ public JaegerExporter(JaegerExporterOptions options)
             this.JaegerAgentUdpBatcher = new JaegerUdpBatcher(options);
         }
 
-        internal IJaegerUdpBatcher JaegerAgentUdpBatcher { get; }
+        internal JaegerUdpBatcher JaegerAgentUdpBatcher { get; }
 
         public override async Task<ExportResult> ExportAsync(IEnumerable<Activity> activityBatch, CancellationToken cancellationToken)
         {
-            await this.exportLock.WaitAsync().ConfigureAwait(false);
```
Comment (CodeBlanch) [inline src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs:44]: Removed this outer lock. Didn't seem to be adding any value. The spec says we should not call SpanExporter.Export concurrently. We're currently not in compliance with that rule, which I want to fix in my next PR. But there's a lock in Append so this one isn't needed anyway.

File: src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs [hunk 7]
```diff
@@ -37,36 +36,23 @@ public JaegerExporter(JaegerExporterOptions options)
...
+                this.ApplyLibraryResource(libraryResource ?? Resource.Empty);
 
-                    this.libraryResourceApplied = true;
-                }
+                this.libraryResourceApplied = true;
+            }
 
-                foreach (var activity in activityBatch)
-                {
-                    // avoid cancelling here: this is no return point: if we reached this point
```
Comment (CodeBlanch) [inline src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs:58]: Jaeger previously ignored the cancellationToken it was passed. Spec seems to want us to have a timeout mechanism.

File: src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs [hunk 8]
```diff
@@ -90,9 +91,7 @@ private Task SendBatchActivityAsync(IEnumerable<Activity> batchActivity)
                 Content = new JsonContent(this, batchActivity),
             };
 
-            // avoid cancelling here: this is no return point: if we reached this point
```
Comment (CodeBlanch) [inline src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs:93]: Zipkin previously ignored the cancellationToken it was passed. Spec seems to want us to have a timeout mechanism.

File: src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs (hunk 3 above)
Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:244]: mm.. @reyang - whats your thought on this part - we will throw if user is calling ForceFlush with a cancellationtoken and that token is cancelled/expired. The expectation is that user would catch that and handle it.

It possible user forgets this part, (because they heard SDK never throws:) ), and can cause issues. Should we try to be more tolerating here, and catch exception and not bubble it up to user here? 

(agree with the part where we are throwing at initialization part.)

Comment (cijothomas) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:244]: If we end up with the behavior of throwing in this case, lets make a comment stating it can throw exception, in the ForceFlushAsync and ShutdownAsync API.

Comment (CodeBlanch) [reply src/OpenTelemetry/Trace/Export/BatchingActivityProcessor.cs:246]: Added exception comments.
