### PR TITLE
Examples: Fix ParentProvider not being set on MyFilteringProcessor

### LINKED ISSUE #3241: Filtering Processor example is problematic
The [filtering processor example](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#filtering-processor) has some problems.

As noted by @hadashiA, `SetParentProvider` does not not get invoked on the `SimpleActivityExportProcessor` in the example.

Personally, I don't think a processor is a great solution for doing this. Even though the [specification itself suggests](https://github.com/open-telemetry/opentelemetry-specification/blob/c6676e0bfca86cb0fec41c15c9f51bd419bce6d0/specification/trace/sdk.md#span-processor) that filtering is a good use case to satisfy with a span processor:

> SDK MUST allow users to implement and configure custom processors and decorate built-in processors for advanced scenarios such as tagging or filtering.

I'd be more inclined to write my own exporter that does the filtering. For example, you could write an exporter that wrapped the OTLP exporter. Your exporter would do the filtering and forward to the underlying exporter.

I think replacing the example with an example of a custom exporter that does filtering may be a better solution than trying to provide a mechanism to set the provider.

_Originally posted by @alanwest in https://github.com/open-telemetry/opentelemetry-dotnet/discussions/3201#discussioncomment-2664044_

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #3241

## Changes

Uses `CompositeProcessor<Activity>` so that `ParentProvider` is correctly set on the inner processor for the filtering example.

Requires https://github.com/open-telemetry/opentelemetry-dotnet/pull/3368#issuecomment-1156984436 to fully work.

### CODE REVIEW

File: docs/trace/extending-the-sdk/MyFilteringProcessor.cs [hunk 1]
```diff
@@ -18,15 +18,14 @@
 using System.Diagnostics;
 using OpenTelemetry;
 
-internal class MyFilteringProcessor : BaseProcessor<Activity>
+internal class MyFilteringProcessor : CompositeProcessor<Activity>
```
Comment (reyang) [inline docs/trace/extending-the-sdk/MyFilteringProcessor.cs:21]: Purely from the reader's perspective - I guess folks would question "why would I need to derive from CompositeProcessor?".

Comment (alanwest) [reply docs/trace/extending-the-sdk/MyFilteringProcessor.cs:21]: 🤔 this is a good question, and I can't think of simple explanation to give users. The alternative to making `SetParentProvider` public is problematic for similar reasons. I'd struggle to come up with a concise way to explain to users under what circumstances they need to be sure to call `SetParentProvider`.

In either case the explanation is basically: if you're newing up a processor and you're not directly passing it to `providerBuilder.AddProcessor()` (i.e., it's nested in another processor or something) then you gotta make sure that the parent provider gets set - which in turn ensures the provider has access to the configured resource... 

but this will raise questions of why the parent provider needs to be set and what does it need access to a resource

Comment (CodeBlanch) [reply docs/trace/extending-the-sdk/MyFilteringProcessor.cs]: I don't have a good solution for this! Agree with @alanwest exposing `SetParentProvider` feels wrong. I just added some XML comments explaining (or hinting at) what is going on in the example. That might help?

We could introduce a class to make it more self-explanatory like...

```csharp
public class DelegatingProcessor<T> : CompositeProcessor<T>
{
   public DelegatingProcessor(BaseProcessor<T> innerProcessor)
      : base(new[] { innerProcessor ?? throw new ArgumentNullException(nameof(innerProcessor) })
   {
   }
}
```

...or...

```csharp
    public class DelegatingProcessor<T> : BaseProcessor<T>
    {
        public DelegatingProcessor(BaseProcessor<T> innerProcessor)
        {
            Guard.ThrowIfNull(innerProcessor);

            this.InnerProcessor = innerProcessor;
        }

        protected BaseProcessor<T> InnerProcessor { get; }

        public override void OnStart(T data)
        {
            this.InnerProcessor.OnStart(data);
        }

        public override void OnEnd(T data)
        {
            this.InnerProcessor.OnEnd(data);
        }

        internal override void SetParentProvider(BaseProvider parentProvider)
        {
            this.InnerProcessor.SetParentProvider(parentProvider);
        }

        protected override bool OnForceFlush(int timeoutMilliseconds)
        {
            return this.InnerProcessor.ForceFlush(timeoutMilliseconds);
        }

        protected override bool OnShutdown(int timeoutMilliseconds)
        {
            return this.InnerProcessor.Shutdown(timeoutMilliseconds);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.InnerProcessor.Dispose();
            }

            base.Dispose(disposing);
        }
    }
```

I doubt anyone will like that either, but it's an option 🤣

**Review by reyang — APPROVED** [review]
Looks _okay_ to me.

File: docs/trace/extending-the-sdk/MyFilteringProcessor.cs (hunk 1 above)
Comment (alanwest) [reply docs/trace/extending-the-sdk/MyFilteringProcessor.cs]: > I doubt anyone will like that either, but it's an option 🤣

Yea not yet excited about this idea. I do agree the naming offers a slight improvement, but I think it's worth sitting on a bit. Definitely think it's worth continuing this discussion in hopes of finding a better solution.

**Review by alanwest — APPROVED** [review]
👍 looks good. At least the example works as intended now! Can't argue with progress.

File: docs/trace/extending-the-sdk/MyFilteringProcessor.cs (hunk 1 above)
Comment (alanwest) [reply docs/trace/extending-the-sdk/MyFilteringProcessor.cs]: Something about this problem kinda feels similar to middleware branching. Like the filter processor effectively introduces a branch in the pipeline. Something like

```csharp
if (filterFunc(span)) {
    // invoke the next process in the chain
} else {
    // terminate the pipeline - maybe call a noop processor or something
}
```
