### PR TITLE
[SDK] Remove the dependency on M.E.C.EnvironmentVariables

### LINKED ISSUE #4084: Consider decoupling EnvariableVariable implementation from the SDK
# Bug Report

OpenTelemetry.dll 1.4.0-rc2 has dependency on Microsoft.Extensions.Configuration.EnvironmentVariables. The suggestion is to move the environment variable implementation and related dependencies to a separate package. The main reason is that environment variable is just one way of doing configurations, later there might be file-based solution or other solutions - keeping them separate will allow the core package to have low footprint, with reduced attack surface and smaller SBOM (Software Bill of Material) - these are important in building trustworthy software.

Consider this as a release blocker for 1.4.0.

https://www.nuget.org/packages/OpenTelemetry/1.4.0-rc.2#dependencies-body-tab

image

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #4084

## Changes

Consumes the bits from Microsoft.Extensions.Configuration.EnvironmentVariables so the SDK doesn't need a dependency.

## TODOs

* [X] Appropriate `CHANGELOG.md` updated for non-trivial changes

### CODE REVIEW

**Review by reyang — APPROVED** [review]

File: src/OpenTelemetry/Internal/EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+{
+    /// <summary>
+    /// An environment variable based <see cref="ConfigurationProvider"/>.
+    /// </summary>
+    internal sealed class EnvironmentVariablesConfigurationProvider : ConfigurationProvider
+    {
+        private const string MySqlServerPrefix = "MYSQLCONNSTR_";
+        private const string SqlAzureServerPrefix = "SQLAZURECONNSTR_";
+        private const string SqlServerPrefix = "SQLCONNSTR_";
+        private const string CustomConnectionStringPrefix = "CUSTOMCONNSTR_";
```
Comment (CodeBlanch) [inline src/OpenTelemetry/Internal/EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs:21]: @alanwest @cijothomas I was just chatting with @reyang about this. So the new feature we are supporting in 1.4.0 is we will look for environment variables using IConfiguration. This code is only ever used for Sdk.Create* style to build IConfiguration from environment variables as backwards compatibility for users without hosting. So strictly speaking, we do not need this connection string logic. We don't support it in 1.3.0 and we don't need to in 1.4.0. Thinking we should remove this and slim it down as a follow-up.

**Review by alanwest — APPROVED** [review]

**Review by cijothomas — COMMENTED** [review]
LGTM

File: src/OpenTelemetry/Internal/EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs (hunk 1 above)
Comment (Yun-Ting) [reply src/OpenTelemetry/Internal/EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs:21]: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4106
