### PR TITLE
Fix bug of recording events of all severity levels in .NET Frameworks in SelfDiagnostics

### LINKED ISSUE #1689: SelfDiagnosticsModule doesn't filter out logs of lower severity level as configured
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* All that has Self Diagnostics modules

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

* All .NET Frameworks has this issue. (All versions of .NET Core are free of this issue.)

## Symptom

Create a file "OTEL_DIAGNOSTICS.json" with content in folder "docs/trace/getting-started":

```json
{
    "LogDirectory": ".",
    "FileSize": 1024,
    "LogLevel": "Error"
}
```

Run command in the same folder: `dotnet run --configuration Release --framework net472 --project getting-started.csproj`

### Bug#1

A file would be generated with content:

```
Successfully opened file.2021-01-09T05:57:36.7394837Z:Activity started. OperationName = '{0}', Id = '{1}'.{Foo}{00-f02701bfe384804ea468f9f4770c6d2e-13c2dca1b5ebc549-01}
2021-01-09T05:57:36.7764812Z:Activity started. OperationName = '{0}', Id = '{1}'.{Bar}{00-f02701bfe384804ea468f9f4770c6d2e-7f5b345dbb1b624a-01}
2021-01-09T05:57:36.7774818Z:Activity started. OperationName = '{0}', Id = '{1}'.{Baz}{00-f02701bfe384804ea468f9f4770c6d2e-74abb7d3cce3f944-01}
2021-01-09T05:57:36.7954830Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Baz}{00-f02701bfe384804ea468f9f4770c6d2e-74abb7d3cce3f944-01}
2021-01-09T05:57:36.8824836Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Bar}{00-f02701bfe384804ea468f9f4770c6d2e-7f5b345dbb1b624a-01}
2021-01-09T05:57:36.8834843Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Foo}{00-f02701bfe384804ea468f9f4770c6d2e-13c2dca1b5ebc549-01}
```

### Bug#2

There is also a separate issue that this file cannot be opened (even in read-only mode) by text editor when the program is running.

Untitled - Notepad 1_12_2021 4_49_57 PM

**What is the expected behavior?**

The issues don't happen for .NET Core: Run command `dotnet run --configuration Release --framework netcoreapp3.1 --project getting-started.csproj`:

A file should be generated with content:

```
Successfully opened file.
```

[Activity started/stopped events](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs#L260-L270) are `Verbose` level. They should be omitted by self diagnostics module when LogLevel is set to Error, according to [EventListener.EnableEvents](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener.enableevents?view=net-5.0) and [EventLevel](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlevel?view=net-5.0) documentation.

The file should be able to be opened, at least in read-only mode.

What did you expect to see?

See above. Running in .NET Frameworks should be the same as in result of .NET Core.

**What is the actual behavior?**

See above.

What did you see instead?

See above.

### PR DESCRIPTION
**Pull request by xiang17**
Fixes Bug#1 in #1689.

**Bug explanation**

In .NET Frameworks, `OpenTelemetrySdkEventSource` class is initialized before `SelfDiagnosticsEventListener` class. (In .NET Core, it's in the opposite order.)

In this case, `SelfDiagnosticsEventListener`'s constructor gets called after its base class (`EventListener`) [constructor](https://referencesource.microsoft.com/#mscorlib/system/diagnostics/eventing/eventsource.cs,4227), which eventually invokes `SelfDiagnosticsEventListener.OnEventSourceCreated` because it overrides `EventListener.OnEventSourceCreated`. The event sources in `OnEventSourceCreated` will always be enabled with `LogAlways`, the default value of [EventLevel enum](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlevel?view=net-5.0).

So `SelfDiagnosticsEventListener.OnEventSourceCreated` doesn't have access to parameters passed to constructor, such as the `LogLevel` configuration. Essentially there is no way to pass any values to `SelfDiagnosticsEventListener.OnEventSourceCreated`. All `EventSource` events of any severity levels will always be captured by `SelfDiagnosticsEventListener`.

## Changes

To honor the configuration, I'm storing the event sources in `OnEventSourceCreated` in an array and enable them in constructor where the configuration values are available.

### CODE REVIEW

**Review by CodeBlanch — APPROVED** [review]
Interesting problem! I think what `EventListener` is doing here is an anti-pattern ([CA2214](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2214)). I guess now we know why 😄

File: src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs [hunk 1]
```diff
@@ -157,6 +174,22 @@ protected override void OnEventSourceCreated(EventSource eventSource)
         {
             if (eventSource.Name.StartsWith(EventSourceNamePrefix, StringComparison.Ordinal))
             {
+                // If there are EventSource classes already initialized as of now, this method would be called from
```
Comment (cijothomas) [inline src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:177]: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/EventCounterCollector/EventCounterCollector/EventCounterListener.cs#L28 similar/same issue in other places. 
Don't recollect if you need to use a Concurrent data structure, or not. (probably no need as an explicit lock is used?)

File: src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs [hunk 2]
```diff
@@ -157,6 +174,22 @@ protected override void OnEventSourceCreated(EventSource eventSource)
...
+                // the base class constructor before the first line of code in SelfDiagnosticsEventListener constructor.
+                // In this case logLevel is always its default value, "LogAlways".
+                // Thus we should save the event source and enable them later, when code runs in constructor.
+                if (this.eventSourcesBeforeConstructor != null)
+                {
+                    lock (this.eventSourcesBeforeConstructor)
```
Comment (cijothomas) [inline src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:183]: a dedicated lock obj instead?

Comment (xiang17) [reply src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:183]: Make sense. I've updated it. Although I didn't make it a static field like the `EventCounterListener` did, because the lock is [used for an instance variable (`eventSourcesBeforeConstructor`)](https://stackoverflow.com/questions/6891711/difference-between-lockthis-and-a-lock-on-static-object). And using static might [cause an unneeded performance hit](https://stackoverflow.com/questions/6891711/difference-between-lockthis-and-a-lock-on-static-object).

File: src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs (hunk 1 above)
Comment (xiang17) [reply src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:178]: I think it's not needed because it's already locked. Either concurrent data structure or a lock works. There could be a performance difference, but I don't think we will have enough number of EventSource sub-classes/instances for the difference to matter.

File: src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs [hunk 3]
```diff
@@ -34,14 +34,32 @@ internal class SelfDiagnosticsEventListener : EventListener
...
         public SelfDiagnosticsEventListener(EventLevel logLevel, SelfDiagnosticsConfigRefresher configRefresher)
         {
             this.logLevel = logLevel;
             this.configRefresher = configRefresher ?? throw new ArgumentNullException(nameof(configRefresher));
+
+            List<EventSource> eventSources;
+            lock (this.lockObj)
+            {
+                eventSources = this.eventSourcesBeforeConstructor;
+                this.eventSourcesBeforeConstructor = null;
```
Comment (cijothomas) [inline src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:52]: Is it possible to have some EventSource created *after* this constructor code is executed? If yes, then we'll miss them, right?

Comment (xiang17) [reply src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:52]: In that case, the code will skip the `if (this.eventSourcesBeforeConstructor != null)` block in `OnEventSourceCreated` method and enable the EventSource objects right there after the if block.

Comment (cijothomas) [reply src/OpenTelemetry/Internal/SelfDiagnosticsEventListener.cs:52]: Got it.

**Review by cijothomas — APPROVED** [review]
