### PR TITLE
OTLP exporter: use Grpc.Net.Client for netstandard2.1

### LINKED ISSUE #1651: OTLP exporter improvements
Currently the constructor for the `OtlpExporter` instantiates a gRPC channel here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/1630fb3abbea6ea7721257e5157afe03686ecaff/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs#L59

The channel constructor can throw an exception. I've encountered this when using a [single file publish](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file):

```shell
dotnet publish -r linux-x64 -p:PublishSingleFile=true
```
Using the single file publish causes this issue in the gRPC library https://github.com/grpc/grpc/issues/24266.

#1616 also suggests that the `OtlpExporter` constructor is throwing an excption. I'm uncertain if it is the same one, but it is most likely the instantiation of the channel that is throwing here too.

Few things I'd like to suggest:

1. Delay the instantiation of the channel to the first call to export data. This would allow us to catch the exception on export and not crash the application.
2. Make a `netstandard2.1` build of the OTLP exporter. This would enable us to use the [grpc-dotnet](https://github.com/grpc/grpc-dotnet) library for .NET 3.1 and above instead of the native [grpc](https://github.com/grpc/grpc/tree/master/src/csharp) library. This would:
    * Resolve the issue with single file publish
    * Provide a better fix for #1251 - which has a work around, but has some dubious security concerns https://github.com/grpc/grpc/issues/21446#issuecomment-698396812
    * And may help #1616 - though I'm not entirely certain of this yet...

### PR DESCRIPTION
**Pull request by alanwest**
Fixes #1651 

## Changes

This PR introduces a `netstandard2.1` build of the OTLP exporter. This enables the exporter to use `Grpc.Net.Client` instead of the native gRPC library for .NET Core 3.0+ applications.

We have had a number of issues with the native gRPC library that are resolved by using `Grpc.Net.Client`. Also, `Grpc.Net.Client` is [reportedly fast on .NET 5](https://devblogs.microsoft.com/aspnet/grpc-performance-improvements-in-net-5/).

This PR does introduce some breaking changes to the `OtlpExporterOptions` which needed to be adapted for use with `Grpc.Net.Client`.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by eddynaka — APPROVED** [review]

File: examples/Console/TestOtlpExporter.cs [hunk 1]
```diff
@@ -53,12 +54,15 @@ internal static object Run(string endpoint)
 
         private static object RunWithActivitySource(string endpoint)
         {
+            // Enable support for unencrypted HTTP2
+            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```
Comment (alanwest) [inline examples/Console/TestOtlpExporter.cs:58]: This is required when calling insecure (i.e. http not https) gRPC service. This is [no longer required for .NET 5](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#call-insecure-grpc-services-with-net-core-client).

I can document this in the readme.

File: examples/Console/TestOtlpExporter.cs [hunk 2]
```diff
@@ -53,12 +54,15 @@ internal static object Run(string endpoint)
...
+
             // Enable OpenTelemetry for the sources "Samples.SampleServer" and "Samples.SampleClient"
             // and use OTLP exporter.
             using var openTelemetry = Sdk.CreateTracerProviderBuilder()
                     .AddSource("Samples.SampleClient", "Samples.SampleServer")
                     .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("otlp-test"))
-                    .AddOtlpExporter(opt => opt.Endpoint = endpoint)
+                    .AddOtlpExporter(opt => opt.Endpoint = new Uri(endpoint))
```
Comment (alanwest) [inline examples/Console/TestOtlpExporter.cs:65]: For the `netstandard2.1` build, I changed the Endpoint to be a `Uri` instead of `string`. This is because if the scheme is not present then the client throws:

```
System.ArgumentException: Only 'http' and 'https' schemes are allowed.
```

I figure using `Uri` helps mitigate this.

File: src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs [hunk 3]
```diff
@@ -25,27 +29,42 @@ namespace OpenTelemetry.Exporter.OpenTelemetryProtocol
...
         /// The valid syntax is described at https://github.com/grpc/grpc/blob/master/doc/naming.md.
         /// </summary>
         public string Endpoint { get; set; } = "localhost:55680";
+#endif
 
+#if NETSTANDARD2_1
+        /// <summary>
+        /// Gets or sets the gRPC channel options.
+        /// </summary>
+        public GrpcChannelOptions GrpcChannelOptions { get; set; }
```
Comment (alanwest) [inline src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs:50]: The `GrpcChannelOptions` class in `Grpc.Net.Client` should cover functionality previously covered with the `Credentials` and `ChannelOptions` configuration options.

File: src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs [hunk 4]
```diff
@@ -37,7 +40,11 @@ public class OtlpExporter : BaseExporter<Activity>
         private const string DefaultServiceName = "OpenTelemetry Exporter";
 
         private readonly OtlpExporterOptions options;
+#if NETSTANDARD2_1
+        private readonly GrpcChannel channel;
+#else
         private readonly Channel channel;
+#endif
```
Comment (nrcventura) [inline src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs:47]: Just a minor thing...You don't need to use the compiler directives here if you use ChannelBase instead of the specific Channel types.
```suggestion
        private readonly ChannelBase channel;
```

Comment (alanwest) [reply src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs:47]: We call `ShutdownAsync` on the channel here https://github.com/open-telemetry/opentelemetry-dotnet/blob/64777d3220da41e3573b32e7d83c39061c9b6dcd/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs#L157

This is not a method on `ChannelBase`. Are you familiar with a different pattern for managing the lifetime of the channel?

Comment (nrcventura) [reply src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs:47]: It looks like ShutdownAsync is defined on ChannelBase.
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/ChannelBase.cs#L53-L68

Comment (alanwest) [reply src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs:47]: Ah, yes ok I see what's going on. The net45, net46 and netstandard2.0 builds of the exporter depend on an older version (2.23.0) of the grpc library. `ShutdownAsync` was added after this version here https://github.com/grpc/grpc/commit/abeac187b6744302ff73ca20897f11c816cb3801#diff-218ffbfa6d10bb57abf89df29e76a18a0785a03c38952c219a84c08aada89545.

It might make sense to update the version, but I think makes sense as a separate concern from this PR

**Comment by alanwest** [comment]
We lack test coverage for sending data with a legit gRPC client - even prior to this PR. The existing unit tests all use this mock `NoopTraceServiceClient`

https://github.com/open-telemetry/opentelemetry-dotnet/blob/7a91923fb7a1ee6fbc75b6fdc145137e93b38917/test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs#L417

I'd like to expand the coverage here, but haven't had a chance yet. I've manually tested the work in this PR pretty extensively. Depending on what folks would prefer, I can either expand the test coverage as part of this PR or in a follow up.

File: examples/Console/TestOtlpExporter.cs (hunk 1 above)
Comment (CodeBlanch) [reply examples/Console/TestOtlpExporter.cs]: It would probably be good to have that note in the README.

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Review by cijothomas — APPROVED** [review]
LGTM.
Separately, we can modify the readme and examples to show both pre 3.0 and post 3.0 app code snippets, to help when people upgrade to newer .net versions?
