### PR TITLE
Logs: Add log record pooling

### LINKED ISSUE #1582: Perf improvements for LogRecord
LogRecord is implemented as a class (allocated on the GC heap) instead of a struct (allocated on the stack).
This avoids copy for batch exporting scenario, and also helps on getting a better alignment with tracing part (where Activity is a class) which simplifies the code. However it could potentially punish perf for non-batch scenario (e.g. piping logs to ETW or LTTng).

One possible solution is to have a pre-allocated collection of LogRecord objects, and keep using them. This could be done either using thread local storage or a global collection (array or something else).

### LINKED ISSUE #2905: [Logs] ObjectDisposedException when using ParseStateValues
When using `ParseStateValues` option for logging the app crash
```
Unhandled exception. System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
```

image

- TargetFramework: net6.0
- "OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc9"
- "OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9"

### PR DESCRIPTION
**Pull request by CodeBlanch**
[Goal is to pare down the amount of changes on #3305]

Fixes #1582
Fixes #2905

## Changes

* Adds two `LogRecord` pool implementations. One uses a `ThreadStatic` and the other implements a circular buffer. The type of pool to use is determined by the processor(s) registered with `OpenTelemetryLoggerProvider`.
* Buffers state values when using batch exporter or in-memory exporter.

## TODOs

* [X] Appropriate `CHANGELOG.md` updated for non-trivial changes

### CODE REVIEW

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+                    // pool. Anything lost in the race will collected by the GC
+                    // and the pool will issue new instances as needed
+                    this.pool[returnSnapshot % this.Capacity] = logRecord;
+                    return;
+                }
+            }
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        public void TrackReference(LogRecord logRecord)
```
Comment (reyang) [inline src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:110]: Could this be static?

Comment (reyang) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:110]: Or maybe move it to `LogRecord.AddRef`?

**Review by reyang — APPROVED** [review]
LGTM with a changelog entry.

File: src/OpenTelemetry.Exporter.InMemory/InMemoryExporterLoggingExtensions.cs [hunk 2]
```diff
@@ -42,9 +42,17 @@ private static ExportResult ExportLogRecord(in Batch<LogRecord> batch, ICollecti
 
             foreach (var log in batch)
             {
-                log.BufferLogScopes();
+                log.Buffer();
 
-                exportedItems.Add(log);
+                LogRecord copy = new()
```
Comment (TimothyMothra) [inline src/OpenTelemetry.Exporter.InMemory/InMemoryExporterLoggingExtensions.cs:47]: consider moving this to the LogRecord class.
I think it would be easier to maintain a copy ctor.
`internal LogRecord(LogRecord other)`

Comment (CodeBlanch) [reply src/OpenTelemetry.Exporter.InMemory/InMemoryExporterLoggingExtensions.cs]: I refactored it into `class LogRecord { internal LogRecord Copy() {} }`. In-memory exporter has to see SDK internals to invoke the method but we already had that in place 😄 LMK what you think about that.

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 3]
```diff
@@ -219,6 +221,24 @@ public void ForEachScope<TState>(Action<LogRecordScope, TState> callback, TState
...
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal void AddReference()
+        {
+            Interlocked.Increment(ref this.PoolReferenceCount);
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal int RemoveReference()
```
Comment (reyang) [inline src/OpenTelemetry/Logs/LogRecord.cs:237]: Minor, I personally found AddRef/Release commonly used, might be related to C++ only:

* https://www-archive.mozilla.org/projects/xpcom/book/cxc/html/appb#1151263
* https://www-archive.mozilla.org/projects/xpcom/book/cxc/html/appb#1125183
* https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-addref

File: src/OpenTelemetry/Batch.cs [hunk 4]
```diff
@@ -90,7 +91,11 @@ public void Dispose()
                 // Drain anything left in the batch.
                 while (this.circularBuffer.RemovedCount < this.targetCount)
                 {
-                    this.circularBuffer.Read();
+                    T item = this.circularBuffer.Read();
+                    if (typeof(T) == typeof(LogRecord))
```
Comment (utpilla) [inline src/OpenTelemetry/Batch.cs:95]: Maybe use a `boolean` field like `isLogBatch` to decide if we need to return the item to the pool instead of checking it for each item of the batch?

File: src/OpenTelemetry/Batch.cs [hunk 5]
```diff
@@ -140,6 +145,29 @@ public struct Enumerator : IEnumerator<T>
...
             };
 
+            private static readonly BatchEnumeratorMoveNextFunc MoveNextCircularBufferLogRecord = (ref Enumerator enumerator) =>
+            {
+                var circularBuffer = enumerator.circularBuffer;
+
+                var currentItem = enumerator.Current;
+                if (currentItem != null)
+                {
+                    if (typeof(T) == typeof(LogRecord))
```
Comment (TimothyMothra) [inline src/OpenTelemetry/Batch.cs:155]: I see `typeof(T) == typeof(LogRecord)` repeated in a few places. The others are Dispose method or ctor, but this one in the MoveNext seems like it would get hit often.

Consider moving this to a `private readonly bool IsLogRecord`.

Comment (utpilla) [inline src/OpenTelemetry/Batch.cs:155]: Is this check required here?

The Enumerator ctor already has this check:
```csharp
this.moveNextFunc = typeof(T) == typeof(LogRecord) ? MoveNextCircularBufferLogRecord : MoveNextCircularBuffer;
```

**Review by TimothyMothra — APPROVED** [review]
LGTM

File: src/OpenTelemetry/Batch.cs [hunk 6]
```diff
@@ -140,6 +145,29 @@ public struct Enumerator : IEnumerator<T>
...
+                    {
+                        LogRecordSharedPool.Current.Return((LogRecord)(object)currentItem);
```
Comment (TimothyMothra) [inline src/OpenTelemetry/Batch.cs:157]: This extra casting bugs me. Likely not an easy fix for this.
I wonder if we would benefit from having a `class LogRecordBatch : Batch<LogRecord>` to avoid the extra type checks.
Probably out of scope for this PR. :)

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs (hunk 1 above)
Comment (reyang) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs]: Looks good to me, I have a minor comment regarding naming https://github.com/open-telemetry/opentelemetry-dotnet/pull/3385#discussion_r903112020.

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 7]
```diff
@@ -213,22 +221,77 @@ public void ForEachScope<TState>(Action<LogRecordScope, TState> callback, TState
...
+        private void BufferLogScopes()
         {
-            if (this.ScopeProvider == null || this.bufferedScopes != null)
+            if (this.ScopeProvider == null)
             {
                 return;
             }
 
-            List<object?> scopes = new List<object?>();
+            List<object?> scopes = this.BufferedScopes ??= new List<object?>(16);
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/LogRecord.cs:290]: Why 16?

File: src/OpenTelemetry/Logs/OpenTelemetryLogger.cs [hunk 8]
```diff
@@ -77,22 +90,30 @@ public bool IsEnabled(LogLevel logLevel)
...
+                    return attributeStorage;
+                }
             }
             else
             {
-                return new List<KeyValuePair<string, object?>>
-                {
-                    new KeyValuePair<string, object?>(string.Empty, state),
-                };
+                var attributeStorage = logRecord.AttributeStorage ??= new List<KeyValuePair<string, object?>>(8);
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:114]: Why 8?

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 7 above)
Comment (utpilla) [reply src/OpenTelemetry/Logs/LogRecord.cs:290]: Okay. I learnt that it's the maximum number of scopes allowed. Maybe use: `LogRecordSharedPool.DefaultMaxNumberOfScopes`?

Comment (utpilla) [reply src/OpenTelemetry/Logs/LogRecord.cs:290]: Also, how is the list capacity restricted to 16? `AddScopeToBufferedList` is simply adding the scope to the list. It will just resize the list if it keeps adding more scopes to it, right?

File: src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+            }
+
+            return new();
+        }
+
+        public void Return(LogRecord logRecord)
+        {
+            if (Storage == null)
+            {
+                LogRecordSharedPool.Clear(logRecord);
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs:50]: Move the `Clear` method to `LogRecordPool` as it's applicable to both the classes?

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs [hunk 10]
```diff
@@ -0,0 +1,172 @@
...
+            if (attributeStorage != null)
+            {
+                if (attributeStorage.Count > DefaultMaxNumberOfAttributes)
+                {
+                    // Don't allow the pool to grow unconstained.
+                    logRecord.AttributeStorage = null;
+                }
+                else
+                {
+                    /* List<T>.Clear sets the size to 0 but it maintains the
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:119]: nit: rename "size" to "Count".

File: src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs [hunk 11]
```diff
@@ -182,6 +190,29 @@ internal OpenTelemetryLoggerProvider AddProcessor(BaseProcessor<LogRecord> proce
...
+            {
+                var current = compositeProcessor.Head;
+                while (current != null)
+                {
+                    if (this.ContainsBatchProcessor(current.Value))
+                    {
+                        return true;
+                    }
+
+                    current = current.Next;
```
Comment (alanwest) [inline src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:209]: I guess this may be improbable but still possible - might have a concurrency issue here in the event another thread changes the value of `Next`.

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs [hunk 12]
```diff
@@ -57,9 +57,14 @@ public override void OnEnd(LogRecord data)
...
 
-            data!.BufferLogScopes();
+            data!.Buffer();
 
-            base.OnEnd(data);
+            data.AddReference();
+
+            if (!this.TryExport(data))
+            {
+                LogRecordSharedPool.Current.Return(data);
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:66]: I think we should decrement the reference count before calling returning the data to pool here.

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 13]
```diff
@@ -213,22 +221,77 @@ public void ForEachScope<TState>(Action<LogRecordScope, TState> callback, TState
...
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal void ResetReferenceCount()
+        {
+            this.PoolReferenceCount = 1;
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal void AddReference()
+        {
+            Interlocked.Increment(ref this.PoolReferenceCount);
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/LogRecord.cs:233]: Do we expect multiple threads to update reference count of the same logRecord object simultaneously?

Reset and Increment should always be called from the thread calling `ILogger.Log`.

Decrement which is called by return would also be called from the same thread that called `ILogger.Log` with the only exception being the exporter thread which would also call `Return` but there shouldn't be any other thread operating on the same logRecord object at that time.

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs [hunk 14]
```diff
@@ -0,0 +1,172 @@
...
+
+                if (rentSnapshot >= returnSnapshot)
+                {
+                    break; // buffer is empty
+                }
+
+                if (Interlocked.CompareExchange(ref this.rentIndex, rentSnapshot + 1, rentSnapshot) == rentSnapshot)
+                {
+                    var logRecord = Interlocked.Exchange(ref this.pool[rentSnapshot % this.Capacity], null);
+                    if (logRecord == null && !this.TryRentCoreRare(rentSnapshot, out logRecord))
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:60]: I think this can be simplified by using `CompareExchange` instead of `Exchange` for retrieving a logRecord object from the pool:

```diff
+            LogRecord? logRecord = null;
            while (true)
            {
                var rentSnapshot = Volatile.Read(ref this.rentIndex);
                var returnSnapshot = Volatile.Read(ref this.returnIndex);
+               var recordToRent = this.pool[rentSnapshot % this.Capacity];

                if (rentSnapshot >= returnSnapshot)
                {
                    break; // buffer is empty
                }

                if (Interlocked.CompareExchange(ref this.rentIndex, rentSnapshot + 1, rentSnapshot) == rentSnapshot)
                {
-                    var logRecord = Interlocked.Exchange(ref this.pool[rentSnapshot % this.Capacity], null);
-                    if (logRecord == null && !this.TryRentCoreRare(rentSnapshot, out logRecord))
-                    {
-                        continue;
-                    }
+                    if (Interlocked.CompareExchange(ref this.pool[rentSnapshot % this.Capacity], null, recordToRent) == recordToRent)
+                    {
+                        logRecord = recordToRent;
+                    }

+                    if (logRecord == null)
+                    {
+                        continue;
+                    }

                    logRecord!.ResetReferenceCount();

                    return logRecord;
                }
            }
```

File: src/OpenTelemetry/Batch.cs (hunk 4 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Batch.cs:95]: That would actual perform worse! What is going on here... JIT magic 🧙‍♂️ What happens is when `Batch<LogRecord>` is JITted, all of these type checks become constant things. For `T`s != `LogRecord` they are completely removed. When `T` == `LogRecord` the checks are removed and the logic is just inlined.

Here is a [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4a9BsXKDREqXwDCEfB3EAbGFCYGAbuLAxcs6nIDMC0g3UMA3jQbuFd4BAi6GAWQAKAEoXNw8I43YGcQwYfAYAXgYRGAB3Bi4IAHMBGEgoABMQqwiIgCFsDDAWAB4s3PzoQoA+BmAqmqSU9MDY+ODSsvcO6pY+ABFxXA4IXBgS8OHiAHYYuPwNfWwRAFUOdWxdfUKh9wBfGkvrWjtcDCghMAxMnLyCwppXagjiLx8/OptnsDkcTi4GNkYBhpAwOFBxFE4gx5jCGNcIksGABtfzQlgQQoASW0ukCeIwBOJpIA8hwJBARLg+AA5CBEkS6cQibnZYIAXSxfwUKEcwKEHBCWO+w3clOmWxgO32h2OMEK3QeQhkWOu11sKK1zwYAEFnojYgBPL5XGg0bEAKViAHEYKkEWBAhhLRwYBAAGaBBrvZrBAX2p0YV3usxen1+wNmiSmb1hwW3Q2PY2VMa1AAqbRADCJUxmc14+htP3c8MRVRgDFg2EKjN0loYefW8TOS2FOZqgU7/XwwSWMrK8uZw+6w7OGPcvbsxFFpdm8yl1bCm484n9DDjvoDg9CiWS3sPgeDTSKYax7nHssCQbe18KwUCEGAACt8hhgpO+GHYJFR2CVFm3C4lj1IA) attempting to demo the concept.

In the final JIT Asm notice...

For `Batch<LogRecord>` the logic is being executed:

```
Batch`1[[LogRecord, _]].Dispose()
    L0000: sub rsp, 0x28
    L0004: xor eax, eax
    L0006: mov [rsp+0x20], rax
    L000b: movzx ecx, byte ptr [rcx]
    L000e: mov [rsp+0x20], cl
    L0012: lea rcx, [rsp+0x20]
    L0017: call 0x00007ffd192404c0
    L001c: nop
    L001d: add rsp, 0x28
    L0021: ret
```

For `Batch<Activity>` the logic is completely removed:

```
Batch`1[[Activity, _]].Dispose()
    L0000: ret
```

File: src/OpenTelemetry/Batch.cs (hunk 5 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Batch.cs:155]: See my comment above. All of these type checks are strategic for the JIT to optimize them away.

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+    /// <summary>
+    /// Manages a pool of <see cref="LogRecord"/> instances.
+    /// </summary>
+    public static class LogRecordPool
+    {
+        /// <summary>
+        /// Resize the pool.
+        /// </summary>
+        /// <param name="capacity">The maximum number of <see cref="LogRecord"/>s to store in the pool.</param>
+        public static void Resize(int capacity)
```
Comment (utpilla) [inline src/OpenTelemetry/Logs/Pool/LogRecordPool.cs:32]: Is it okay to expose a public API that could allocate a huge array at runtime post-startup?

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 7 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs]: I think my naming might have confused things a bit. There isn't a maximum per `LogRecord` being processed. If a `LogRecord` has 1000 attributes and 100 scopes, they will all be added and handed to the exporter. What the "max" values on the pool control is what we'll keep around in the pool. So that `LogRecord` with 1000/100 will have its attributes/scopes `null`ed out when returned to the pool. Essentially the pool is constrained but individual `LogRecord`s are not.

Why 64/16? I just pulled those numbers out of the air. Tried to come up with something reasonable that would fit most use cases.

I did update to use the constant here. Let me know if given the above explanation you think other changes could help.

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs (hunk 10 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs]: I updated the comment so hopefully it is more clear now.

File: src/OpenTelemetry/Batch.cs (hunk 4 above)
Comment (utpilla) [reply src/OpenTelemetry/Batch.cs:95]: Ahh that's great!

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs (hunk 15 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordPool.cs:35]: 🤷 You have an alternative in mind?

I added this because I thought there might be users interested in fine-tuning the pool. But we could make it internal initially and see if anyone asks. I'm surprised not more people commenting on it 😄

Comment (cijothomas) [reply src/OpenTelemetry/Logs/Pool/LogRecordPool.cs:35]: It'd be good to start without exposing this publicly.

If there is an ask (eg: https://github.com/dotnet/runtime/issues/65264), we can expose it then.

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 7 above)
Comment (utpilla) [reply src/OpenTelemetry/Logs/LogRecord.cs]: I understood it now. I can't think of any other changes that could help other than maybe just renaming the variable to something like `DefaultInitialNumberOfScopes`.

File: src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs (hunk 11 above)
Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:209]: There is the current behavior of `AddProcessor`:
1. If multiple threads are calling `AddProcessor` simultaneously, the caller should be responsible for doing proper synchronization (this follows the .NET general approach - member functions are not thread safe by default).
2. It is safe if a thread is calling `AddProcessor` while other threads are using the processors (e.g. by generating Activity objects which go through the processor chain).

And here is my general thinking regarding thread safety:
1. All the telemetry APIs must be thread safe, following the OpenTelemetry spec:
    * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#concurrency
    * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#concurrency-requirements
2. Any other APIs (e.g. the APIs exposed by the SDK package) should follow .NET general guidance, which is:
    * static method should be thread safe
    * member function will not be thread safe
3. Certain functions might provide additional thread safety guarantees in addition to 2), and this should be called out explicitly in the API XML document:
    https://github.com/open-telemetry/opentelemetry-dotnet/blob/9bb7aaf727e64ce738f1113e7b1a10df681bf794/src/OpenTelemetry/BaseExporter.cs#L76-L79

File: src/OpenTelemetry/Logs/OpenTelemetryLogger.cs (hunk 8 above)
Comment (utpilla) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:114]: Yeah, I guess we could stay consistent with scopes. We could use the constant variable here and have it updated to 8 if need be.

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs [hunk 16]
```diff
@@ -0,0 +1,77 @@
...
+        {
+            Guard.ThrowIfOutOfRange(capacity, min: 1);
+
+            LogRecordSharedPool.Current = new(capacity);
+        }
+
+        internal static void Clear(LogRecord logRecord)
```
Comment (cijothomas) [inline src/OpenTelemetry/Logs/Pool/LogRecordPool.cs:42]: this could be moved to a utility/helper class.

File: src/OpenTelemetry/Batch.cs (hunk 5 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Batch.cs:155]: @utpilla I did a little more investigation on this.

Ran this through SharpLab:

```csharp
[JitGeneric(typeof(LogRecord))]
[JitGeneric(typeof(Activity))]
public class Helpers<T>
{
   public void DisposeActionLogRecord(T item)
   {
      ((LogRecord)(object)item).Cleanup();
   }  
   
   public void DisposeActionLogRecordWithCheck(T item)
   {
      if (typeof(T) == typeof(LogRecord))
      {
          ((LogRecord)(object)item).Cleanup();
      }
   }     
    
   public void DisposeAction(T item)
   {
   }
}
```

For T == LogRecord...

```
Helpers`1[[LogRecord, _]].DisposeActionLogRecord(LogRecord)
    L0000: sub rsp, 0x28
    L0004: xor eax, eax
    L0006: mov [rsp+0x20], rax
    L000b: mov [rsp+0x20], dl
    L000f: lea rcx, [rsp+0x20]
    L0014: call 0x00007ffd197804d0
    L0019: nop
    L001a: add rsp, 0x28
    L001e: ret

Helpers`1[[LogRecord, _]].DisposeActionLogRecordWithCheck(LogRecord)
    L0000: sub rsp, 0x28
    L0004: xor eax, eax
    L0006: mov [rsp+0x20], rax
    L000b: mov [rsp+0x20], dl
    L000f: lea rcx, [rsp+0x20]
    L0014: call 0x00007ffd197804d0
    L0019: nop
    L001a: add rsp, 0x28
    L001e: ret

Helpers`1[[LogRecord, _]].DisposeAction(LogRecord)
    L0000: ret
```

Method with and without the type check look the same.

For T == Activity...

```
Helpers`1[[Activity, _]].DisposeActionLogRecord(Activity)
    L0000: push rdi
    L0001: push rsi
    L0002: sub rsp, 0x28
    L0006: xor eax, eax
    L0008: mov [rsp+0x20], rax
    L000d: mov esi, edx
    L000f: mov rcx, 0x7ffd1978d278
    L0019: call 0x00007ffd6e75b080
    L001e: mov rdi, rax
    L0021: mov [rdi+8], sil
    L0025: mov rdx, rdi
    L0028: mov rcx, 0x7ffd1978d178
    L0032: call 0x00007ffd0ebb7478
    L0037: movzx ecx, byte ptr [rdi+8]
    L003b: mov [rsp+0x20], cl
    L003f: lea rcx, [rsp+0x20]
    L0044: call 0x00007ffd197804d0
    L0049: nop
    L004a: add rsp, 0x28
    L004e: pop rsi
    L004f: pop rdi
    L0050: ret

Helpers`1[[Activity, _]].DisposeActionLogRecordWithCheck(Activity)
    L0000: ret

Helpers`1[[Activity, _]].DisposeAction(Activity)
    L0000: ret
```

Interesting, eh? Without the type check the JIT generated a lot of stuff. Probably a cast with a throw if the cast fails.

I'm thinking I'm going to change the code from...

```csharp
            private static readonly BatchEnumeratorMoveNextFunc MoveNextCircularBufferLogRecord = (ref Enumerator enumerator) =>
            {
                var circularBuffer = enumerator.circularBuffer;

                var currentItem = enumerator.Current;
                if (currentItem != null)
                {
                    if (typeof(T) == typeof(LogRecord))
                    {
                        LogRecordSharedPool.Current.Return((LogRecord)(object)currentItem);
                    }
                }

                if (circularBuffer!.RemovedCount < enumerator.targetCount)
                {
                    enumerator.current = circularBuffer.Read();
                    return true;
                }

                enumerator.current = null;
                return false;
            };
```

...to...

```csharp
            private static readonly BatchEnumeratorMoveNextFunc MoveNextCircularBufferLogRecord = (ref Enumerator enumerator) =>
            {
                if (typeof(T) == typeof(LogRecord))
                {
                    var circularBuffer = enumerator.circularBuffer;

                    var currentItem = enumerator.Current;
                    if (currentItem != null)
                    {
                        LogRecordSharedPool.Current.Return((LogRecord)(object)currentItem);
                    }

                    if (circularBuffer!.RemovedCount < enumerator.targetCount)
                    {
                        enumerator.current = circularBuffer.Read();
                        return true;
                    }

                    enumerator.current = null;
                }

                return false;
            };
```

By placing the type check over the whole block the JIT _should_ understand it doesn't need to generate anything for batches of activity/metric which will lead to less memory being taken up by code that will never execute. How you feel about that?

File: src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs (hunk 11 above)
Comment (alanwest) [reply src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:209]: 👍 makes sense. Agreed we should follow .NET's guidance here.

Different concern, but same area of code... someone could do the following:

```csharp
var processor = new OpenTelemetry.CompositeProcessor<LogRecord>(new SomeProcessor());
loggerProvider.AddProcessor(processor);
processor.AddProcessor(new OpenTelemetry.BatchLogRecordExportProcessor(new SomeExporter()));
```

The provider would end up using use the `ThreadStaticPool`, correct? Maybe this is far fetched as well and not worth doing anything about 😆. I suppose it would require constantly inspecting for any changes to the processor pipeline.

Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:209]: Ya that's a problem. Could add an event on `CompositeProcessor` like `internal EventHandler ProcessorAdded` we could fire and use to listen for changes. Just an idea, not going to do anything on this PR to address it.

Comment (alanwest) [reply src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:209]: You probably won't like this idea, but could drop the `ThreadStaticPool` for now - if we went with the event solution, definitely seems fit for its own PR. I assume the SharedPool would still have perf benefits even when no batching is involved.

That said, not a blocker at all, I think it's probably fine to roll with this as a known edge case - the thing is, I _think_ it's an edge case. I haven't encountered users who are modifying their processor pipeline after initialization.

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 13 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs:233]: `AddReference` should always be called serially. But `RemoveReference` there could be racing. Here is what I'm thinking about...

* The thread emitting the log will flow to [OnExport](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2e334df8aec79831ca3660f294dab8fa1e1920d1/src/OpenTelemetry/BatchExportProcessor.cs#L107) which _could_ trigger an export on the dedicated thread. Or the export thread could just decide to wake up right after the log is added to the batch. The emitting thread will call `Return` a bit further along in its call path as will the exporter thread after it exports the log. Those `Return`s could race.

* There could be multiple exporters. Each will fire on its own thread and call `Return` _whenever_ they happen to finish processing. Those `Return`s could race.

So I think using the `Interlocked` operations for reference counting are good to keep it safe?

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs (hunk 12 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:66]: So at the moment `Return` decrements the reference count. If it is `!= 0` then it no-ops. If it is `== 0` then it returns. So if I move that logic out, anywhere `Return` is called has to do more work. Something like...

```csharp
if (logRecord.RemoveReference() == 0)
{
   LogRecordSharedPool.Current.Return(data);
}
```

There are currently 5 places where `Return` is called. 1 more for `LogEmitter` (not on this PR).

I don't love duplicating that logic all over the place. What if I renamed the method `Return` -> `TryReturn` to better indicate what is going on?

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs [hunk 17]
```diff
@@ -0,0 +1,172 @@
...
+                }
+
+                if (Interlocked.CompareExchange(ref this.returnIndex, returnSnapshot + 1, returnSnapshot) == returnSnapshot)
+                {
+                    // If many threads are hammering rent/return it is possible
+                    // for two threads to write to the same index. In that case
+                    // only one of the logRecords will make it back into the
+                    // pool. Anything lost in the race will collected by the GC
+                    // and the pool will issue new instances as needed
+                    this.pool[returnSnapshot % this.Capacity] = logRecord;
```
[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:99]: I like this idea, however I think it might be optimizing for the wrong case. The race called out in the comment is for "many threads hammering rent/return" which is more of a theoretic exercise. The actual use (right now) is many threads renting/reading (log emitters), one thread returning/writing (batch exporter). In that scenario, this race should really never be hit. So if we put in the `Interlocked.CompareExchange` that is more expensive than just doing `this.pool[returnSnapshot % this.Capacity] = logRecord` which should work for actual use case we have right now. Are you open to me updating the comment with the solution and considerations so we have it captured (in the event the use case changes) but we leave as-is for now so we have better perf for exporters returning records?

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 3 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs:237]: How passionately do you feel about this? I looked around, don't see any good example or prior art in .NET. `AddRef` w/ `Release` seems a bit odd for me for a .NET API. `AddRef` and `RemoveRef` I think would be better?

Comment (reyang) [reply src/OpenTelemetry/Logs/LogRecord.cs:237]: only 1% 😄

Comment (reyang) [reply src/OpenTelemetry/Logs/LogRecord.cs:237]: Btw, this is a good article https://docs.microsoft.com/en-us/windows/win32/com/rules-for-managing-reference-counts

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs (hunk 15 above)
Comment (cijothomas) [reply src/OpenTelemetry/Logs/Pool/LogRecordPool.cs:35]: Following the general principle of not exposing anything until there is a spec, or super strong need - lets keep this internal to begin with.

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs (hunk 16 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordPool.cs]: I just renamed this class `LogRecordPoolHelper` for you 😄

File: src/OpenTelemetry/Logs/Pool/LogRecordPool.cs (hunk 15 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordPool.cs]: Updated

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:114]: Just updated the comment with more details.

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs [hunk 18]
```diff
@@ -57,9 +57,14 @@ public override void OnEnd(LogRecord data)
             // happen here.
             Debug.Assert(data != null, "LogRecord was null.");
 
-            data!.BufferLogScopes();
+            data!.Buffer();
```
Comment (cijothomas) [inline src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:60]: lets add a TODO to add a targeted test for testing https://github.com/open-telemetry/opentelemetry-dotnet/issues/2905

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 19]
```diff
@@ -213,22 +221,77 @@ public void ForEachScope<TState>(Action<LogRecordScope, TState> callback, TState
...
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        internal int RemoveReference()
+        {
+            return Interlocked.Decrement(ref this.PoolReferenceCount);
+        }
+
+        internal void Buffer()
+        {
+            this.BufferLogStateValues();
```
Comment (cijothomas) [inline src/OpenTelemetry/Logs/LogRecord.cs:244]: add a comment/todo for "state" - do we need to do similar for state as well?

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 20]
```diff
@@ -213,22 +221,77 @@ public void ForEachScope<TState>(Action<LogRecordScope, TState> callback, TState
...
+        private void BufferLogStateValues()
+        {
+            var stateValues = this.StateValues;
+            if (stateValues == null || stateValues == this.AttributeStorage)
+            {
+                return;
+            }
+
+            var attributeStorage = this.AttributeStorage ??= new List<KeyValuePair<string, object?>>(stateValues.Count);
+            attributeStorage.AddRange(stateValues);
```
Comment (cijothomas) [inline src/OpenTelemetry/Logs/LogRecord.cs:275]: add a comment this is what triggers the iteration/enumeration to "snap" what we need before things could get disposed.

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs (hunk 12 above)
Comment (utpilla) [reply src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:66]: I was actually referring to this particular situation where adding the data to the Circular buffer fails. I was still wrong though. I got a little confused as the `Return` here would always be a no-op (as reference count is 2) but I then realized that the `Return` in `OpenTelemetryLogger.Log` would work:

```csharp
if (!this.TryExport(data))
{
    LogRecordSharedPool.Current.Return(data);
}
```

**Review by cijothomas — APPROVED** [review]
LGTM!
Left few nits, mostly about adding comments or todo.

File: src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs (hunk 14 above)
Comment (utpilla) [reply src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs:68]: Sure.

> That could lead to a higher rate of misses under load which would reduce throughput. But harder to test that.

I think we could use some Stress Tests to measure that later.

File: src/OpenTelemetry/Batch.cs (hunk 5 above)
Comment (utpilla) [reply src/OpenTelemetry/Batch.cs]: Great finding!

**Review by utpilla — APPROVED** [review]

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs (hunk 18 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:60]: I had some tests I did on #2932 so I just updated and added them to this PR.

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 19 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs:249]: Updated

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 20 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs:296]: Updated
