### PR TITLE
OpenTelemetryLoggerProvider is now unaffected by changes to OpenTelemetryLoggerOptions after the LoggerFactory is built.

### LINKED ISSUE #2902: Disallow `LogRecord` options to be updated after initialization.
# Bug Report
Currently, the SDK allows `LogRecord` options to be changed after the object was being built by the LoggerFactory.
This could introduce unnecessary complexity toward different states (before/after options got updated) and making it harder to maintain.

Discussion: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2891#discussion_r805084530

**What is the expected behavior?**
Remove existing test code on changing the `LogRecord` options after the object was being built by the LoggerFactory in `LogRecordTest.cs and `OtlpLogExporterTests.cs`.

(To be discussed)
Explicitly disallow `LogRecord` options to be tweaked after instantiation.

### PR DESCRIPTION
**Pull request by TimothyMothra**
Fixes #2902.

## Changes
- `OpenTelemetryLoggerProvider` will now copy the values from `OpenTelemetryLoggerOptions`. This prevents changes to the Provider after being initialized.
- Updated tests. Some tests that were testing both true/false values needed to be broken up into two tests.
- Added new tests to verify that changing Options after initializing the Provider don't affect the Provider.

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

## Options

I investigated 3 options.

- Option 1, 
ctor of LoggerProvider copies Options to local fields.
Logger.Log references `this.provider.<local fields>`.
This introduces an ldfld.

- Option 2,
ctor of LoggerProvider copies Options to local fields.
ctor of Logger copies Options to local fields.
Logger.Log references `this.<local fields>`.

- Option 3,
ctor of LoggerProvider copies Options to local fields.
Logger.Log first creates a local var for the provider `var provider = this.provider` then references all other properties/fields from the local var `provider.<local fields>`.
This was done in an attempt to mitigate the ldfld.

## Benchmarks

Test

For this test, I initialized the Provider and Logger.
For the benchmark, I invoke the hotpath (Logger.Log) which accesses the Options.

```
(ran benchmarks twice) 

|              Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|----------:|
|           Unchanged | 47.29 ns | 0.654 ns | 0.580 ns | 0.0102 |      64 B |
|       Option1_ldfld | 48.05 ns | 0.452 ns | 0.401 ns | 0.0102 |      64 B |
|   Option2_localCopy | 48.77 ns | 0.311 ns | 0.291 ns | 0.0102 |      64 B |
| Option3_varProvider | 46.99 ns | 0.411 ns | 0.385 ns | 0.0102 |      64 B |


|              Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|----------:|
|           Unchanged | 45.71 ns | 0.504 ns | 0.472 ns | 0.0102 |      64 B |
|       Option1_ldfld | 47.41 ns | 0.529 ns | 0.495 ns | 0.0102 |      64 B |
|   Option2_localCopy | 45.70 ns | 0.443 ns | 0.393 ns | 0.0102 |      64 B |
| Option3_varProvider | 46.18 ns | 0.567 ns | 0.531 ns | 0.0102 |      64 B |
```

The results are inconclusive, I'm seeing a negligible difference between implementations.

<details>
  <summary>Benchmark code</summary>
  
  ```csharp
    [MemoryDiagnoser]
    public class LogBenchmarks2
    {
        private readonly ILogger loggerUnchanged;
        private readonly ILogger loggerLdfld;
        private readonly ILogger loggerLocalCopy;
        private readonly ILogger loggerVarProvider;

        public LogBenchmarks2()
        {
            var options = new OpenTelemetryLoggerOptions
            {
                IncludeFormattedMessage = true,
                IncludeScopes = true,
                ParseStateValues = true,
            };

            var provider = new OpenTelemetryLoggerProvider(options);
            this.loggerUnchanged = new OpenTelemetryLogger("categoryName", provider);

            var provider2 = new OpenTelemetryLoggerProvider2(options);
            this.loggerLdfld = new OpenTelemetryLogger_LDFLD("categoryName", provider2);
            this.loggerLocalCopy = new OpenTelemetryLogger_LocalCopy("categoryName", provider2);
            this.loggerVarProvider = new OpenTelemetryLogger_VarProvider("categoryName", provider2);
        }

        [Benchmark]
        public void Unchanged()
        {
            this.loggerUnchanged.LogInformation("Hello from {name} {price}.", "tomato", 2.99);
        }

        [Benchmark]
        public void Option1_ldfld()
        {
            this.loggerLdfld.LogInformation("Hello from {name} {price}.", "tomato", 2.99);
        }

        [Benchmark]
        public void Option2_localCopy()
        {
            this.loggerLocalCopy.LogInformation("Hello from {name} {price}.", "tomato", 2.99);
        }

        [Benchmark]
        public void Option3_varProvider()
        {
            this.loggerVarProvider.LogInformation("Hello from {name} {price}.", "tomato", 2.99);
        }
    }
  ```

Option 1: 
```csharp
internal class OpenTelemetryLogger_LDFLD : ILogger

public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
    if (!this.IsEnabled(logLevel)
        || Sdk.SuppressInstrumentation)
    {
        return;
    }

    var processor = this.provider.Processor;
    if (processor != null)
    {
        var record = new LogRecord(
            this.provider.IncludeScopes ? this.ScopeProvider : null,
            DateTime.UtcNow,
            this.categoryName,
            logLevel,
            eventId,
            this.provider.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
            this.provider.ParseStateValues ? null : state,
            exception,
            this.provider.ParseStateValues ? this.ParseState(state) : null);

        processor.OnEnd(record);

        record.ScopeProvider = null;
    }
}
```

Option 2: 
```csharp
internal class OpenTelemetryLogger_LocalCopy : ILogger

internal OpenTelemetryLogger_LocalCopy(string categoryName, OpenTelemetryLoggerProvider2 provider)
{
    Guard.ThrowIfNull(categoryName);
    Guard.ThrowIfNull(provider);

    this.categoryName = categoryName;
    this.provider = provider;

    this.IncludeScopes = provider.IncludeScopes;
    this.IncludeFormattedMessage = provider.IncludeFormattedMessage;
    this.ParseStateValues = provider.ParseStateValues;
}

public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
    if (!this.IsEnabled(logLevel)
        || Sdk.SuppressInstrumentation)
    {
        return;
    }

    var processor = this.provider.Processor;
    if (processor != null)
    {
        var record = new LogRecord(
            this.IncludeScopes ? this.ScopeProvider : null,
            DateTime.UtcNow,
            this.categoryName,
            logLevel,
            eventId,
            this.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
            this.ParseStateValues ? null : state,
            exception,
            this.ParseStateValues ? this.ParseState(state) : null);

        processor.OnEnd(record);

        record.ScopeProvider = null;
    }
}
```

Option 3
```csharp
internal class OpenTelemetryLogger_VarProvider : ILogger

public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
    if (!this.IsEnabled(logLevel)
        || Sdk.SuppressInstrumentation)
    {
        return;
    }

    var provider = this.provider;
    var processor = provider.Processor;
    if (processor != null)
    {
        var record = new LogRecord(
            provider.IncludeScopes ? this.ScopeProvider : null,
            DateTime.UtcNow,
            this.categoryName,
            logLevel,
            eventId,
            provider.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
            provider.ParseStateValues ? null : state,
            exception,
            provider.ParseStateValues ? this.ParseState(state) : null);

        processor.OnEnd(record);

        record.ScopeProvider = null;
    }
}
```
</details>

## IL

The IL code is a bit more revealing.
Option 1 introduces additional `ldfld` when accessing every field.

Original, Option 2, and Option 3 are nearly identical.

```
ORIGINAL
	IL_002d: callvirt instance bool OpenTelemetry.Logs.OpenTelemetryLoggerOptions::get_IncludeScopes()

OPTION 1: LDFLD
	IL_0024: ldfld class OpenTelemetry.Logs.OpenTelemetryLoggerProvider2 OpenTelemetry.Logs.OpenTelemetryLogger_LDFLD::provider
	IL_0029: ldfld bool OpenTelemetry.Logs.OpenTelemetryLoggerProvider2::IncludeScopes

OPTION 2: LOCAL COPY
	IL_0021: ldfld bool OpenTelemetry.Logs.OpenTelemetryLogger_LocalCopy::IncludeScopes

OPTION 3: VAR PROVIDER
	IL_0023: ldfld bool OpenTelemetry.Logs.OpenTelemetryLoggerProvider2::IncludeScopes
```

Considering this, I'm recommending Option 3.

### CODE REVIEW

File: src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs [hunk 1]
```diff
@@ -48,7 +50,10 @@ internal OpenTelemetryLoggerProvider(OpenTelemetryLoggerOptions options)
         {
             Guard.ThrowIfNull(options);
 
-            this.Options = options;
+            this.IncludeScopes = options.IncludeScopes;
```
Comment (cijothomas) [inline src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:53]: Did you add a test targeting this change? I see a lot of test change, not sure if it was modifying existing ones alone, or there is on dedicated to testing the bug fix in this PR.

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs:53]: No, those changes were just to fix the tests that this change broke.

I'll add new tests to verify my change.

**Review by cijothomas — APPROVED** [review]
LGTM once a changelog entry is added

File: src/OpenTelemetry/CHANGELOG.md [hunk 2]
```diff
@@ -24,6 +24,10 @@
   `readonly`
   ([#3065](https://github.com/open-telemetry/opentelemetry-dotnet/pull/3065))
 
+* `OpenTelemetryLoggerProvider` now copies values from `OpenTelemetryLoggerOptions`.
+  This prevents changes to the Provider after being initialized.
```
Comment (cijothomas) [inline src/OpenTelemetry/CHANGELOG.md:28]:
```suggestion
  Provider will not respect changes made after the LoggerFactory is built.
```

**Review by cijothomas — APPROVED** [review]

File: src/OpenTelemetry/Logs/OpenTelemetryLogger.cs [hunk 3]
```diff
@@ -49,18 +49,16 @@ public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Except
...
                 var record = new LogRecord(
-                    options.IncludeScopes ? this.ScopeProvider : null,
+                    this.provider.IncludeScopes ? this.ScopeProvider : null,
                     DateTime.UtcNow,
                     this.categoryName,
                     logLevel,
                     eventId,
-                    options.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
-                    options.ParseStateValues ? null : state,
+                    this.provider.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
```
Comment (reyang) [inline src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: The `this.provider` is used multiple times here which caused multiple `ldfld` IL to be generated.

Need to 1) measure the perf given this is on hot path 2) reduce the cost

**Review by reyang — DISMISSED** [review]
Perf concern on hotpath https://github.com/open-telemetry/opentelemetry-dotnet/pull/3055/files#r830227799

File: src/OpenTelemetry/Logs/OpenTelemetryLogger.cs (hunk 3 above)
Comment (cijothomas) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: It should be easy to avoid this by having these fields in the Logger class itself.

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: I can see several options. In general we need to make sure that any modifications on the hot path are measured against perf impact (and if the noise level is high, we need to find better way to measure instead of drifting to poor perf).

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: @reyang @cijothomas do you have any advice for running the Benchmarks?
I'm doing back-to-back runs and getting different results.

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: Where is the benchmark code?

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: I found BenchmarkDotNet's [best practices](https://benchmarkdotnet.org/articles/guides/good-practices.html).
I shut down most of my programs and got much more consistent results.

I was following the instructions [here](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/test/Benchmarks) and running the tests in [LogBenchmarks.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/Benchmarks/Logs/LogBenchmarks.cs)




### main branch
```
|                                 Method |       Mean |     Error |     StdDev |  Gen 0 | Allocated |
|--------------------------------------- |-----------:|----------:|-----------:|-------:|----------:|
|                             NoListener |  65.527 ns | 1.3479 ns |  2.7836 ns | 0.0101 |      64 B |
|   NoListenerWithLoggerMessageGenerator |   5.247 ns | 0.1241 ns |  0.1740 ns |      - |         - |
|                           OneProcessor | 172.858 ns | 3.3029 ns |  4.5211 ns | 0.0370 |     232 B |
| OneProcessorWithLoggerMessageGenerator | 138.863 ns | 2.8119 ns |  6.2309 ns | 0.0267 |     168 B |
|                          TwoProcessors | 186.247 ns | 3.7727 ns | 10.7026 ns | 0.0370 |     232 B |
|                        ThreeProcessors | 183.196 ns | 3.6586 ns |  8.9747 ns | 0.0370 |     232 B |
```


### WITH this.options `ldfld`
```
|                                 Method |       Mean |     Error |     StdDev |  Gen 0 | Allocated |
|--------------------------------------- |-----------:|----------:|-----------:|-------:|----------:|
|                             NoListener |  63.320 ns | 1.1267 ns |  1.5794 ns | 0.0101 |      64 B |
|   NoListenerWithLoggerMessageGenerator |   4.862 ns | 0.0757 ns |  0.0708 ns |      - |         - |
|                           OneProcessor | 159.104 ns | 3.1748 ns |  5.5605 ns | 0.0370 |     232 B |
| OneProcessorWithLoggerMessageGenerator | 135.320 ns | 2.6625 ns |  5.0657 ns | 0.0267 |     168 B |
|                          TwoProcessors | 160.163 ns | 2.8330 ns |  3.6837 ns | 0.0370 |     232 B |
|                        ThreeProcessors | 196.035 ns | 4.1022 ns | 11.7039 ns | 0.0370 |     232 B |
```

### WITH copying fields to the Logger class
```
|                                 Method |       Mean |     Error |    StdDev |  Gen 0 | Allocated |
|--------------------------------------- |-----------:|----------:|----------:|-------:|----------:|
|                             NoListener |  59.460 ns | 1.1879 ns | 1.6653 ns | 0.0101 |      64 B |
|   NoListenerWithLoggerMessageGenerator |   4.888 ns | 0.1231 ns | 0.1152 ns |      - |         - |
|                           OneProcessor | 156.369 ns | 2.6028 ns | 2.1735 ns | 0.0370 |     232 B |
| OneProcessorWithLoggerMessageGenerator | 121.974 ns | 2.0873 ns | 1.9524 ns | 0.0267 |     168 B |
|                          TwoProcessors | 161.967 ns | 3.0390 ns | 2.5377 ns | 0.0370 |     232 B |
|                        ThreeProcessors | 156.933 ns | 1.7382 ns | 1.5408 ns | 0.0370 |     232 B |
```

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: Thanks, I'll unblock this PR. Please include the following things in the PR description:
1. what are the possible options.
2. what's the perf analysis for each options.
3. why would you go with a certain option, what's the perf difference before/after.

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: Here goes a good example #2805

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: @reyang @cijothomas I updated the description with more targeted benchmarks.
The results are inconclusive, I'm seeing a negligible difference between implementations.
Is this good enough to proceed?

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: Where is the benchmark code? Consider following what's done in https://github.com/dotnet/runtime/issues/67207:

image

Comment (reyang) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: > The results are inconclusive, I'm seeing a negligible difference between implementations.

This is essentially telling us the measurement was performed in the incorrect place or the tool is insufficient for this kind of task.

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: updated. 

side note, currently looking for a tool to inspect the IL code

Comment (TimothyMothra) [reply src/OpenTelemetry/Logs/OpenTelemetryLogger.cs:58]: After reviewing the IL, I can see that Option 1 introduced several extra `ldfld` which was Reiley's concern.

The Original implementation is nearly identical to Options 2 & 3. 

```
ORIGINAL
	IL_002d: callvirt instance bool OpenTelemetry.Logs.OpenTelemetryLoggerOptions::get_IncludeScopes()

OPTION 1: LDFLD
	IL_0024: ldfld class OpenTelemetry.Logs.OpenTelemetryLoggerProvider2 OpenTelemetry.Logs.OpenTelemetryLogger_LDFLD::provider
	IL_0029: ldfld bool OpenTelemetry.Logs.OpenTelemetryLoggerProvider2::IncludeScopes

OPTION 2: LOCAL COPY
	IL_0021: ldfld bool OpenTelemetry.Logs.OpenTelemetryLogger_LocalCopy::IncludeScopes

OPTION 3: VAR PROVIDER
	IL_0023: ldfld bool OpenTelemetry.Logs.OpenTelemetryLoggerProvider2::IncludeScopes
```

I believe the best approach is to create a local `var provider` from which all other fields/properties can be accessed.

```csharp
            var provider = this.provider;
            var processor = provider.Processor;
            if (processor != null)
            {
                var record = new LogRecord(
                    provider.IncludeScopes ? this.ScopeProvider : null,
                    DateTime.UtcNow,
                    this.categoryName,
                    logLevel,
                    eventId,
                    provider.IncludeFormattedMessage ? formatter?.Invoke(state, exception) : null,
                    provider.ParseStateValues ? null : state,
                    exception,
                    provider.ParseStateValues ? this.ParseState(state) : null);

                processor.OnEnd(record);

                record.ScopeProvider = null;
            }
```

**Review by reyang — APPROVED** [review]
LGTM.

File: test/OpenTelemetry.Tests/Logs/LoggerOptionsTest.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+        [InlineData(false)]
+        public void VerifyOptionsCannotBeChangedAfterInit(bool initialValue)
+        {
+            var options = new OpenTelemetryLoggerOptions
+            {
+                IncludeFormattedMessage = initialValue,
+                IncludeScopes = initialValue,
+                ParseStateValues = initialValue,
+            };
+            var processor = new OpenTelemetryLoggerProvider(options);
```
Comment (cijothomas) [inline test/OpenTelemetry.Tests/Logs/LoggerOptionsTest.cs:35]: nit: typo?

File: test/OpenTelemetry.Tests/Logs/LogRecordTest.cs [hunk 5]
```diff
@@ -30,38 +30,15 @@
 
 namespace OpenTelemetry.Logs.Tests
 {
-    public sealed class LogRecordTest : IDisposable
+    public sealed class LogRecordTest
```
Comment (cijothomas) [inline test/OpenTelemetry.Tests/Logs/LogRecordTest.cs:33]: The loggerfactory was disposed in IDisposable impln. It does not look like factory is disposed in the new tests.

**Review by cijothomas — CHANGES_REQUESTED** [review]
Code changes looks good (Thanks for addressing the perf issues !)
The test changes does not seem to be disposing the factory. This needs to be fixed before we merge.

File: test/OpenTelemetry.Tests/Logs/LogRecordTest.cs (hunk 5 above)
Comment (TimothyMothra) [reply test/OpenTelemetry.Tests/Logs/LogRecordTest.cs:33]: changed the helper method to return the factory. calling method is responsible for using `using`

File: test/OpenTelemetry.Tests/Logs/LogRecordTest.cs [hunk 6]
```diff
@@ -595,7 +595,7 @@ public void ParseStateValuesUsingCustomTest()
             Assert.Same(state, actualState.Value);
         }
 
-        private static void InitializeLoggerFactory(out ILogger logger, out List<LogRecord> exportedItems, Action<OpenTelemetryLoggerOptions> configure = null)
+        private static ILoggerFactory InitializeLoggerFactory(out ILogger logger, out List<LogRecord> exportedItems, Action<OpenTelemetryLoggerOptions> configure = null)
```
Comment (cijothomas) [inline test/OpenTelemetry.Tests/Logs/LogRecordTest.cs:598]: why do we have to have the helper method create a ILogger? It can just do what it claims to do (from the name) - initialize and return a loggerfactory, configured as per the `configure` action given to it.

Comment (TimothyMothra) [reply test/OpenTelemetry.Tests/Logs/LogRecordTest.cs:598]: This was meant to simplify the individual tests by removing a dozen lines of identical boilerplate code.
I can move some or all of this into every test, but I don't think that improves the value of the tests themselves.

**Review by cijothomas — APPROVED** [review]

File: test/OpenTelemetry.Tests/Logs/LogRecordTest.cs (hunk 6 above)
Comment (cijothomas) [reply test/OpenTelemetry.Tests/Logs/LogRecordTest.cs]: The name of the helper method did not indicate its intended purpose. The latest commit looks better.
(if we want to achieve less duplication in tests, we can do that, with aptly named helper. but this looks good for me now)
