### PR TITLE
[OpenTelemetry] Fix assertion failures in debug

### LINKED ISSUE #6300: [bug] Debug.Assert failure in MetricReaderEx.cs
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                         | 1.12.0   |

### Runtime Version

net8.0 (probably all TFMs)

### Description

Running `dotnet test` in the root of the repository, which uses the `Debug` configuration, a number of tests fail due to this assertion failing:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/d5f67321185bd90d49481974fa9dd3082b214548/src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs#L213

### Steps to Reproduce

Run `dotnet test` from the root of the repository.

### Expected Result

Assertion does not fire, tests pass.

### Actual Result

Test run is interrupted by the failed assertion dialog being raised multiple times.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by martincostello**
Fixes #6300

## Changes

Avoid failing assertions in debug by skipping collecting a metrics batch if the `MeterProvider` has not yet been initialized.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by rajkumar-rangaraj** [comment]
@CodeBlanch Could you please review this PR? In my opinion `Debug.Assert` shouldn't be a concern here.

**Comment by martincostello** [comment]
@CodeBlanch Could you take a look at this PR please? It's been stuck for about 6 weeks.

File: src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs [hunk 1]
```diff
@@ -209,8 +209,11 @@ private void CreateOrUpdateMetricStreamRegistration(in MetricStreamIdentity metr
 
     private Batch<Metric> GetMetricsBatch()
     {
-        Debug.Assert(this.metrics != null, "this.metrics was null");
-        Debug.Assert(this.metricsCurrentBatch != null, "this.metricsCurrentBatch was null");
```
Comment (CodeBlanch) [inline src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs]: The assumption here is that this case is impossible when the SDK is actually running. So what we're effectively doing with this change is taking a runtime perf hit to fix issues arising from test structure. I would vote instead we fix the structure of tests to match what actually happens at runtime.

Comment (martincostello) [reply src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs]: I'm still digging through the tests to try and work out which ones are specifically causing the assertion failures, but the root cause is that `PeriodicExportingMetricReader` starts a thread in its constructor:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/8321588b2808bede8f2b018f286eb78b2f3dfd14/src/OpenTelemetry/Metrics/Reader/PeriodicExportingMetricReader.cs#L50-L57

If it gets scheduled/runs before the code that changes the state that causes the assertions not to fire then they'll fire. I'm not sure that can be 100% fixed in all scenarios without changing the exporter itself, which I think (it's been nearly 3 months since I opened this PR at this point) is why I changed the assertions rather than changed whatever was causing them.

Comment (martincostello) [reply src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs]: I think fundamentally the assertions that are being made here with respect to the tests are unsound.

`this.metrics` and `this.metricsCurrentBatch` can only ever be non-null if `ApplyParentProviderSettings()` is invoked - this is only ever invoked in one place, here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/8321588b2808bede8f2b018f286eb78b2f3dfd14/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L82-L86

That code is in the constructor of `MeterProviderSdk()`, which can only be initialized with an `IServiceProvider` and has interdependencies on other setup within it related to other concrete types (like `MeterProviderBuilderSdk`).

As `PeriodicExportingMetricReader` starts a thread unconditionally, that effectively makes it impossible to construct into a valid state without access to and knowledge of the SDK internals.

I've pushed up a change that leaves the asserts as-is by instead just making the arrays non-null on construction, where they get overwritten if/when `ApplyParentProviderSettings()` is called. As the compiler checks for null I think that then makes those assertions redundant and could be removed, but I've left them in place.

I think the tests as currently written are just highlighting a flaw in the design that assumes very specific code paths are used that are unenforceable.

**Review by rajkumar-rangaraj — APPROVED** [review]
