### PR TITLE
[logs] Fix pooling issues when wrapping batch export processor

### LINKED ISSUE #5250: [logs] Wrapped batch processor doesn't trigger correct log pool
I worked through an issue with a user who wrapped the `BatchLogRecordExportProcessor` in a custom processor:

```csharp
    configure.AddProcessor(new FilteringProcessor<LogRecord>(new BatchLogRecordExportProcessor(exporter), ShouldUpload));

    internal sealed class FilteringProcessor<T> : BaseProcessor<T>
    {
        private readonly BaseProcessor<T> inner;
        private readonly Func<T, bool> filter;

        public FilteringProcessor(BaseProcessor<T> inner, Func<T, bool> filter)
        {
            this.inner = inner;
            this.filter = filter;
        }

        public override void OnEnd(T activity)
        {
            // Call the underlying processor
            // only if the Filter returns true.
            if (this.filter(activity))
            {
                this.inner.OnEnd(activity);
            }
        }
    }
```

In that case the SDK fails to switch into "shared pool" mode: https://github.com/open-telemetry/opentelemetry-dotnet/blob/eab0a7c36762becbee788fdc4fdb69c4d578b738/src/OpenTelemetry/Logs/LoggerProviderSdk.cs#L172

## Workaround

```csharp
    configure.AddProcessor(new FilteringBatchLogRecordProcessor(ShouldUpload, exporter));

    internal sealed class FilteringBatchLogRecordProcessor : BatchLogRecordExportProcessor
    {
        private readonly Func<LogRecord, bool> filter;

        public FilteringBatchLogRecordProcessor(Func<LogRecord, bool> filter, BaseExporter<LogRecord> exporter)
            : base(exporter)
        {
            this.filter = filter;
        }

        public override void OnEnd(LogRecord logRecord)
        {
            // Call the underlying processor
            // only if the Filter returns true.
            if (this.filter(logRecord))
            {
                base.OnEnd(logRecord);
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #5250

## Changes

* Updates `BatchLogRecordExportProcessor` and `Batch<T>` to only return `LogRecord`s to the shared pool if they were rented from it.

## Details

If the SDK [detects a batch processor it switches to a shared pool of LogRecords](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0a77cc3cced0be0a24dd54cd4707cf71c2b97314/src/OpenTelemetry/Logs/LoggerProviderSdk.cs#L98-L103). This works fine for all of the OOB stuff and registration extensions. However if you wrap the `BatchLogRecordExportProcessor` inside some other processor (see #5250) it won't be detected and the SDK will choose the `ThreadStatic` pool.

What this PR does is make `BatchLogRecordExportProcessor` and `Batch<T>` aware that it might be used with non-pooled records.

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [X] Unit tests added/updated
* [X] Appropriate `CHANGELOG.md` files updated for non-trivial changes

### CODE REVIEW

File: src/OpenTelemetry/Logs/LogRecord.cs [hunk 1]
```diff
@@ -80,6 +81,15 @@ internal LogRecord()
         }
     }
 
+    internal enum LogRecordSource
+    {
+#pragma warning disable SA1602 // Enumeration items should be documented
```
Comment (TimothyMothra) [inline src/OpenTelemetry/Logs/LogRecord.cs:86]: Is a pragma disable _really_ necessary here? 😄

File: src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs [hunk 2]
```diff
@@ -19,15 +21,20 @@ public LogRecord Rent()
         var logRecord = Storage;
         if (logRecord != null)
         {
+            Debug.Assert(logRecord.Source == LogRecord.LogRecordSource.FromThreadStaticPool, "logRecord.Source was not FromThreadStaticPool");
             Storage = null;
             return logRecord;
         }
 
-        return new();
+        return new()
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs:29]: nit: As it is a return for readability specify the type instead of just new.

File: src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs [hunk 3]
```diff
@@ -42,13 +42,27 @@ public override void OnEnd(LogRecord data)
...
+                data.Buffer();
+                this.TryExport(data);
+                break;
+            default:
+                Debug.Assert(data.Source == LogRecord.LogRecordSource.FromThreadStaticPool, "LogRecord source was something unexpected");
 
-        if (!this.TryExport(data))
-        {
-            LogRecordSharedPool.Current.Return(data);
+                // Note: If we are using ThreadStatic pool we make a copy of the record.
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs:63]: Out of curiosity, why do we need to make a copy when using ThreadStaticPool?

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 1 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs:86]: Opened this PR to loosen the requirements: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5256

File: src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs (hunk 2 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs]: I rewrote it a bit to try and improve the readability. Check it out LMK

File: src/OpenTelemetry/CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,11 @@
   state for cumulative temporality.
   [#5230](https://github.com/open-telemetry/opentelemetry-dotnet/pull/5230)
 
+* Fixed an issue causing `LogRecord`s to be incorrectly reused when wrapping an
```
Comment (vishweshbankwar) [inline src/OpenTelemetry/CHANGELOG.md:16]: Could you specify if there is a way to detect if someone is running in to this issue?

File: src/OpenTelemetry/Logs/LogRecord.cs (hunk 1 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/Logs/LogRecord.cs]: Ended up adding docs. Not sure if that PR will land.

**Review by rajkumar-rangaraj — APPROVED** [review]
LGTM

**Review by Kielek — APPROVED** [review]

File: src/OpenTelemetry/CHANGELOG.md (hunk 4 above)
Comment (CodeBlanch) [reply src/OpenTelemetry/CHANGELOG.md:16]: There isn't a super easy way to detect the issue. Records rented from the `ThreadStatic` pool have their attributes cleared when returned so most users will observe log records without attributes. But there could be a race too where you would get data from some other log. I added "which leads to missing or incorrect data during export" to the CHANGELOG entry how's that?

Comment (vishweshbankwar) [reply src/OpenTelemetry/CHANGELOG.md:16]: This is more clear. Thanks!

File: test/OpenTelemetry.Tests/Logs/LogRecordSharedPoolTests.cs [hunk 5]
```diff
@@ -45,7 +45,7 @@ public void RentReturnTests()
         Assert.Equal(1, pool.Count);
 
         // Note: This is ignored because logRecord manually created has PoolReferenceCount = int.MaxValue.
-        LogRecord manualRecord = new();
+        LogRecord manualRecord = new() { Source = LogRecord.LogRecordSource.FromSharedPool };
```
Comment (vishweshbankwar) [inline test/OpenTelemetry.Tests/Logs/LogRecordSharedPoolTests.cs:48]: Is this a valid scenario? What will be the scenario when logRecord created manually will have source as `FromSharedPool`

Comment (CodeBlanch) [reply test/OpenTelemetry.Tests/Logs/LogRecordSharedPoolTests.cs]: I tweaked the test to be a little more realistic.

**Review by vishweshbankwar — APPROVED** [review]
