### PR TITLE
[ASP.NET Core] Do not reset baggage on request stop event

### LINKED ISSUE #2992: Unable to log baggages via a processor
# Bug Report

List of packages below,
```
<PackageReference Include="OpenTelemetry" Version="1.2.0-rc3" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-rc3" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9" />
```

Runtime version: **net6.0**

## Symptom

I'm trying to use a custom processor like the following to see the baggages that are being propagated. However in this processor `Baggage.Current` is not present to process the baggages.
```
public class TelemetryBaggageLogger : BaseProcessor<Activity>
{
    private readonly ILogger<TelemetryBaggageLogger> _logger;
    
    public TelemetryBaggageLogger(ILogger<TelemetryBaggageLogger> logger)
    {
	    _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }
    
    public override void OnStart(Activity activity)
    {
	    _logger.LogInformation("-------------------> Logging Baggages In BaseProcessor:OnStart <-------------------");
            IDictionaryEnumerator baggageEnumerator = Baggage.Current.GetEnumerator();
            while (baggageEnumerator.MoveNext())
            {
                _logger.LogInformation($"OnStart->Received baggage {baggageEnumerator.Key}:{baggageEnumerator.Value}");
            }
    }
    
    public override void OnEnd(Activity activity)
    {
	    _logger.LogInformation("-------------------> Logging Baggages In BaseProcessor:OnEnd <-------------------");
            IDictionaryEnumerator baggageEnumerator = Baggage.Current.GetEnumerator();
            while (baggageEnumerator.MoveNext())
            {
                _logger.LogInformation($"OnEnd->Received baggage {baggageEnumerator.Key}:{baggageEnumerator.Value}");
            }
    }
}
```

I inject the processor as the following in the downstream (destination) service.
```
.AddProcessor(new TelemetryBaggageLogger(logger))
```

However, I can see the baggages propagating if I log the baggage information in the controller of the downstream service but not the processor.

## To Reproduce

Complete code can be found in the [project](https://github.com/pseudonator/Azure-Microservices-Opentelemetry-Demo).

It's a simple set of services, `Library` -> `Catalog`. Library (source service) calls the Catalog API (downstream service) with a set of baggages.
```
Baggage.SetBaggage("test.baggage1", "bag1");
Baggage.SetBaggage("test.baggage2", "bag2");
```

To run the project, use `docker-compose -f docker-compose.yml -f docker-compose.override.yml up`
To start propagating use curl, `curl -iv http://localhost:8002/api/Orders/books`

### PR DESCRIPTION
**Pull request by vishweshbankwar**
Fixes #2992

Follow up https://github.com/open-telemetry/opentelemetry-dotnet/pull/4274#discussion_r1132766169
Ran the stress test using bombardier tool command

`bombardier-windows-amd64.exe -d 12h -r 50 --header="baggage: key=value" <url>`

Monitored the process using `dotnet-counters monitor` for any memory leaks

snippets after ~10 hr run

With this change
image

With main
WithoutChange

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

File: src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs [hunk 1]
```diff
@@ -286,12 +286,6 @@ public void OnStopActivity(Activity activity, object payload)
                 // the one created by the instrumentation.
                 // And retrieve it here, and set it to Current.
             }
-
-            var textMapPropagator = Propagators.DefaultTextMapPropagator;
-            if (textMapPropagator is not TraceContextPropagator)
-            {
-                Baggage.Current = default;
```
Comment (cijothomas) [inline src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs:293]: should this be done at SDK side instead? Could you run stress tests to confirm there are no leaks if we do not remove it at all.

Comment (vishweshbankwar) [reply src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs:293]: I did run stress test. Did not see any leaks.

Comment (vishweshbankwar) [reply src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs:293]: > should this be done at SDK side instead?
Are you referring to OnEnd in SDK? I have not looked in to that but just thinking it will impact all activities as we need to first check the activity ending is ASP.NET Core one.

**Review by CodeBlanch — APPROVED** [review]

File: src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs (hunk 1 above)
Comment (cijothomas) [reply src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs:293]: Baggage should be independent of any activity, so why we need to check which activity is being stopped?

Comment (vishweshbankwar) [reply src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs:293]: Only for ASP.NET Core activity. For other one's we do not do anything right now as well.

File: test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs [hunk 2]
```diff
@@ -474,7 +474,7 @@ public async Task ExtractContextIrrespectiveOfTheFilterApplied()
         }
 
         [Fact]
-        public async Task BaggageClearedWhenActivityStopped()
+        public async Task BaggageIsNotClearedWhenActivityStopped()
```
Comment (alanwest) [inline test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs:477]: Not a blocking comment... but if the instrumentation had never had this behavior, then we likely would never had this test in the first place. Perhaps we just remove this test completely?

**Review by alanwest — APPROVED** [review]
LGTM

**Review by utpilla — APPROVED** [review]
