### PR TITLE
Resource attributes fix

### LINKED ISSUE #1606: ResourceBuilder Attribute Value is lost when using int value
# Bug Report

```xml
      <PackageReference Include="OpenTelemetry.Api" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc1.1" />
```

* Runtime version: `netcoreapp3.1`

## Symptom

When adding Attributes to `ResourceBuilder`, `AddAttributes` accepts `IEnumerable<KeyValuePair<string, object>>`.
**However, when adding a tag with value as `int`, the value is discarded / `null` in jaeger.**
When using a `string` or calling `ToString()` the value is used.

**What is the expected behavior?**

Since the parameter is of type `object` the int value should work.

**What is the actual behavior?**

The integer value is lost.

## Reproduce

```csharp
BackendServiceResource = ResourceBuilder.CreateDefault()
	.AddService(serviceName:ServiceName, serviceInstanceId:ServiceInstanceId, serviceNamespace:ServiceNamespace, serviceVersion:ServiceVersion)
	.AddAttributes(new []
	{
		new KeyValuePair<string, object>("my.foobar1", 1), // will get lost
		new KeyValuePair<string, object>("my.foobar2", "2"),
		new KeyValuePair<string, object>("my.foobar3", 3.ToString()),
	});

// ...

builder.SetResourceBuilder(BackendServiceResource)
//...
```

Result in jaeger `1.21.0`:

grafik

### PR DESCRIPTION
**Pull request by Austin-Tan**
I messed up with Git commands on PR #1647 and accidentally added a whole host of various changes that I could not undo. The work has been recovered here but for discussion, please refer to the conversation in that request.

**This is my first time working on a change that would require a rework of a unit test. Please let me know if I have done that incorrectly.**

Fixes #1606 .

## Changes

Resource Attributes fixed to allow the values of key-value pairs to be of any object type, matching the behavior of Activity's SetTag method.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by eddynaka — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

File: src/OpenTelemetry/Resources/Resource.cs [hunk 1]
```diff
@@ -101,28 +101,33 @@ public Resource Merge(Resource other)
...
+                if (value is float)
+                {
+                    return System.Convert.ToDouble(value, System.Globalization.CultureInfo.InvariantCulture);
+                }
+
+                throw new System.ArgumentException("Attribute value type is not an accepted primitive", keyName);
             }
 
-            return false;
+            throw new System.ArgumentException("Attribute value is null", keyName);
```
Comment (cijothomas) [inline src/OpenTelemetry/Resources/Resource.cs:130]: we need to have a follow up PR where we should throw if key is null as well.
